# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Fabio Campolim
"""The .rmc6f configuration format (manual §4.11). Fixtures are written here
in the documented layout; no file from the RMCProfile package is used."""

import numpy as np
import pytest

import rmcprofile_tools as rt

HEADER = """(Version 6f format configuration file)
(Generated by rmcprofile-skill test)
Metadata date:        05-09-2026
Number of types of atoms:   2
Atom types present:         Na Cl
Number of each atom type:   4 4
Number of moves generated:           0
Number of moves tried:               0
Number of moves accepted:            0
Number of prior configuration saves: 0
Number of atoms:                     8
Supercell dimensions:                1 1 1
Number density (Ang^-3):                 0.044646
Cell (Ang/deg):     5.640000    5.640000    5.640000   90.000000   90.000000   90.000000
Lattice vectors (Ang):
    5.640000    0.000000    0.000000
    0.000000    5.640000    0.000000
    0.000000    0.000000    5.640000
Atoms:
"""
ATOMS = [  # rock salt: Na at (0,0,0)+fcc, Cl at (1/2,0,0)+fcc
    ("Na", 0.0, 0.0, 0.0, 1), ("Na", 0.5, 0.5, 0.0, 2), ("Na", 0.5, 0.0, 0.5, 3), ("Na", 0.0, 0.5, 0.5, 4),
    ("Cl", 0.5, 0.0, 0.0, 5), ("Cl", 0.0, 0.5, 0.0, 6), ("Cl", 0.0, 0.0, 0.5, 7), ("Cl", 0.5, 0.5, 0.5, 8),
]


@pytest.fixture
def nacl_path(tmp_path):
    lines = [HEADER] + [f"{i+1} {el}      {x:.6f}    {y:.6f}    {z:.6f} {site} 0 0 0\n"
                        for i, (el, x, y, z, site) in enumerate(ATOMS)]
    p = tmp_path / "nacl.rmc6f"
    p.write_text("".join(lines), encoding="utf-8")
    return p


def test_read_header_and_atoms(nacl_path):
    cfg = rt.read_rmc6f(nacl_path)
    assert cfg.atom_types == ["Na", "Cl"] and cfg.counts == [4, 4]
    assert cfg.n_atoms() == 8 and cfg.supercell == (1, 1, 1)
    assert cfg.cell == pytest.approx((5.64, 5.64, 5.64, 90.0, 90.0, 90.0))
    assert cfg.density == pytest.approx(0.044646)
    assert cfg.lattice.shape == (3, 3) and cfg.lattice[0, 0] == pytest.approx(5.64)
    assert list(cfg.atoms[:4]) == ["Na"] * 4 and list(cfg.atoms[4:]) == ["Cl"] * 4
    assert cfg.frac[7].tolist() == pytest.approx([0.5, 0.5, 0.5])
    assert cfg.site.tolist() == list(range(1, 9))
    assert cfg.header["Metadata date"] == "05-09-2026"


def test_cartesian_positions(nacl_path):
    cfg = rt.read_rmc6f(nacl_path)
    xyz = cfg.cart()
    assert xyz.shape == (8, 3)
    assert xyz[1].tolist() == pytest.approx([2.82, 2.82, 0.0])


def test_write_then_read_is_identity(nacl_path, tmp_path):
    cfg = rt.read_rmc6f(nacl_path)
    out = tmp_path / "copy.rmc6f"
    cfg.write(out)
    again = rt.read_rmc6f(out)
    assert again.atom_types == cfg.atom_types and again.counts == cfg.counts
    assert np.allclose(again.frac, cfg.frac) and np.allclose(again.lattice, cfg.lattice)
    assert again.site.tolist() == cfg.site.tolist()
    text = out.read_text(encoding="utf-8")
    assert text.startswith("(Version 6f format configuration file)\n")
    assert "Atoms:\n" in text and text.rstrip().endswith("8 0 0 0")


def test_crlf_file_reads_the_same(nacl_path, tmp_path):
    """One shipped tutorial configuration has CRLF endings (docs/02 P-7)."""
    crlf = tmp_path / "crlf.rmc6f"
    raw = nacl_path.read_bytes().replace(b"\r\n", b"\n")      # write_text may already have used CRLF on Windows
    crlf.write_bytes(raw.replace(b"\n", b"\r\n"))
    cfg = rt.read_rmc6f(crlf)
    assert cfg.n_atoms() == 8 and cfg.atom_types == ["Na", "Cl"] and cfg.cellidx[7].tolist() == [0, 0, 0]


def test_program_written_layout(tmp_path):
    """RMCProfile's own output puts a bracketed flag after the label and no site
    or cell columns: 'index label [1] x y z'; the header order also differs."""
    head = HEADER.replace("Metadata date:        05-09-2026\n", "").replace(
        "Number of prior configuration saves: 0\n", "Accumulated time (s) in running loop: 0.01\nNumber of prior configuration saves: 0\n")
    body = "".join(f"{i+1:6d}   {el}  [1]  {x:.15f}  {y:.15f}  {z:.15f}\n" for i, (el, x, y, z, _) in enumerate(ATOMS))
    p = tmp_path / "prog.rmc6f"
    p.write_text(head + body, encoding="utf-8")
    cfg = rt.read_rmc6f(p)
    assert cfg.n_atoms() == 8 and cfg.frac[1].tolist() == pytest.approx([0.5, 0.5, 0.0])
    assert cfg.site.tolist() == [0] * 8 and cfg.header["Accumulated time (s) in running loop"] == "0.01"


def test_bragg_with_extra_rows_keeps_npoints(tmp_path):
    """The package's ex_1 .bragg says 1180 points and carries 1184 rows."""
    (tmp_path / "s.bragg").write_text("2    3    42.949    204.0963\nsf6 190k\n6.988141\t1.2862\n6.993734\t1.2865\n6.999328\t1.2869\n", encoding="utf-8")
    b = rt.read_bragg(tmp_path / "s.bragg")
    assert b.npoints == 2 and len(b.x) == 2 and b.x[1] == pytest.approx(6.993734)


def test_rejects_atom_count_mismatch(nacl_path, tmp_path):
    bad = tmp_path / "bad.rmc6f"
    bad.write_text(nacl_path.read_text(encoding="utf-8").replace("Number of atoms:                     8",
                                                                  "Number of atoms:                     9"), encoding="utf-8")
    with pytest.raises(ValueError, match="Number of atoms"):
        rt.read_rmc6f(bad)
