# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Fabio Campolim
"""Extract every figure of the executed chapter notebooks into course/deck/figs/.

Rule 22 of the publishing playbook: every figure shown in the course is
generated by a notebook cell. This script is the only way figures enter the
deck -- it pulls the PNG outputs of the book's chapter notebooks
(``chapters/RMCProfile_NN_*.ipynb`` in order, after ``build/execute.py``) and
writes ``provenance.json`` next to them, mapping each file to its chapter,
section, cell index, figure number, caption and SHA-256.

Figure names are ``s<section>-f<ordinal>.png`` (section number from the
``## N.`` heading, ordinal within that section), so they survive edits that do
not add or remove figures inside a section.

Usage (from rmcprofile-skill/):
    python course/tools/extract_figures.py            # write figures + provenance
    python course/tools/extract_figures.py --check    # exit 1 when figures are stale
    python course/tools/extract_figures.py --notebook chapters/RMCProfile_04_Fitting_Neutron_Data.ipynb  # a subset
"""

import argparse
import base64
import hashlib
import html
import json
import os
import re
import sys

__version__ = "0.5.1"

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(SKILL, "build"))
from assemble import MAIN_KEYS, outputs as _chapter_paths  # noqa: E402

# the book chapters that carry figures, in reading order (chapter 0 has none)
NOTEBOOKS = [_chapter_paths(SKILL)[k] for k in MAIN_KEYS if k != "00"]
FIGDIR = os.path.join(SKILL, "course", "deck", "figs")

HEADING = re.compile(r"^##\s+(\d+)\.\s+(.*)$")


def _html_caption(out):
    """'Figure N. text' from a display(HTML(...)) caption output, else None."""
    data = out.get("data", {})
    if "text/html" not in data:
        return None
    text = "".join(data["text/html"])
    m = re.search(r"<b>\s*Figure\s+(\d+)\.\s*</b>(.*?)</div>", text, re.S)
    if not m:
        return None
    body = re.sub(r"<[^>]+>", "", m.group(2))
    return int(m.group(1)), html.unescape(re.sub(r"\s+", " ", body)).strip()


def catalogue(notebook_paths):
    """Yield one record per PNG output of the given notebooks (a path or a
    list of paths, read in order): chapter, section, ordinal, cell, caption, bytes.

    Captions are read from the notebook's own rendered caption outputs (the
    ``caption()`` helper emits ``<b>Figure N.</b> text`` right after each
    figure), so they are exactly what the notebook shows."""
    if isinstance(notebook_paths, str):
        notebook_paths = [notebook_paths]
    for path in notebook_paths:
        yield from _catalogue_one(path)


def _catalogue_one(notebook_path):
    with open(notebook_path, encoding="utf-8") as f:
        nb = json.load(f)
    chapter = os.path.basename(notebook_path)
    section, heading, ordinal = 0, "", 0
    for idx, cell in enumerate(nb["cells"]):
        src = "".join(cell.get("source", []))
        if cell["cell_type"] == "markdown":
            for line in src.splitlines():
                m = HEADING.match(line.strip())
                if m:
                    section, heading, ordinal = int(m.group(1)), m.group(2).strip(), 0
            continue
        records = []
        for out in cell.get("outputs", []):
            data = out.get("data", {})
            if "image/png" in data:
                png = base64.b64decode("".join(data["image/png"]))
                ordinal += 1
                records.append({
                    "file": f"s{section:02d}-f{ordinal}.png",
                    "chapter": chapter,
                    "section": section,
                    "heading": heading,
                    "cell": idx,
                    "figure": None,
                    "caption": "",
                    "sha256": hashlib.sha256(png).hexdigest(),
                    "bytes": len(png),
                    "png": png,
                })
                continue
            cap = _html_caption(out)
            if cap:
                for r in records:
                    if r["figure"] is None:
                        r["figure"], r["caption"] = cap
                        break
        yield from records


def write(records, figdir, notebook_paths, quiet=False):
    if isinstance(notebook_paths, str):
        notebook_paths = [notebook_paths]
    os.makedirs(figdir, exist_ok=True)
    prov = {"notebooks": [os.path.basename(p) for p in notebook_paths], "figures": {}}
    for r in records:
        with open(os.path.join(figdir, r["file"]), "wb") as f:
            f.write(r["png"])
        prov["figures"][r["file"]] = {k: r[k] for k in
                                      ("chapter", "section", "heading", "cell", "figure", "caption",
                                       "sha256", "bytes")}
        if not quiet:
            print(f"  {r['file']}  cell {r['cell']:3d}  {r['bytes']:7d} B  §{r['section']} {r['heading'][:50]}")
    with open(os.path.join(figdir, "provenance.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(prov, f, indent=1, ensure_ascii=False)
        f.write("\n")
    return prov


def check(records, figdir):
    """Return a list of problems: missing, stale or orphaned figures."""
    problems = []
    prov_path = os.path.join(figdir, "provenance.json")
    if not os.path.exists(prov_path):
        return ["provenance.json missing -- run extract_figures.py"]
    with open(prov_path, encoding="utf-8") as f:
        prov = json.load(f)["figures"]
    seen = set()
    for r in records:
        seen.add(r["file"])
        path = os.path.join(figdir, r["file"])
        if not os.path.exists(path):
            problems.append(f"missing {r['file']} (cell {r['cell']})")
            continue
        with open(path, "rb") as f:
            on_disk = hashlib.sha256(f.read()).hexdigest()
        if on_disk != r["sha256"]:
            problems.append(f"stale {r['file']}: notebook output changed (cell {r['cell']})")
        if prov.get(r["file"], {}).get("sha256") != r["sha256"]:
            problems.append(f"provenance out of date for {r['file']}")
    for name in sorted(prov):
        if name not in seen:
            problems.append(f"orphan {name}: no longer produced by the notebooks")
    return problems


def build_parser():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--notebook", nargs="+", default=NOTEBOOKS, metavar="IPYNB",
                   help="executed notebook(s) to read, in order (default: every book chapter)")
    p.add_argument("--outdir", default=FIGDIR, help="figure directory (course/deck/figs)")
    p.add_argument("--check", action="store_true",
                   help="do not write; exit 1 if figures or provenance are stale")
    p.add_argument("-q", "--quiet", action="store_true")
    p.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    return p


def main(argv=None):
    a = build_parser().parse_args(argv)
    records = list(catalogue(a.notebook))
    if not records:
        print("no PNG outputs found -- execute the notebooks first (build/execute.py)",
              file=sys.stderr)
        return 1
    if a.check:
        problems = check(records, a.outdir)
        for pr in problems:
            print(pr, file=sys.stderr)
        if not a.quiet:
            print(f"{len(records)} figures checked, {len(problems)} problem(s)")
        return 1 if problems else 0
    prov = write(records, a.outdir, a.notebook, quiet=a.quiet)
    if not a.quiet:
        print(f"ok: {len(prov['figures'])} figures -> {os.path.relpath(a.outdir, SKILL)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
