# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Fabio Campolim
"""rmclite — a small, clean-room Reverse Monte Carlo engine for teaching.

Written from McGreevy & Pusztai, Mol. Simul. 1 (1988) 359 and Tucker et al.,
J. Phys.: Condens. Matter 19 (2007) 335218 (references/rmclite.md). It is a
teaching object: a few hundred to a few thousand atoms, single-atom moves,
partial g(r) on RMCProfile's grid, chi^2 over partial / total G(r) / F(Q)
targets, closest-approach and distance-window constraints, a harmonic bond
potential, Metropolis acceptance. It never claims RMCProfile's speed or
feature set; its calculated functions are RMCProfile's by construction
(same histogram, same weights: scripts/upstream_adapter.py proves it).

Usage:
    python scripts/rmclite.py synth CONFIG.rmc6f [--displace 0.15] [--noise 0.0] [--rmax 8] [--dr 0.02] [--seed 0] [--outdir OUT]
    python scripts/rmclite.py fit   CONFIG.rmc6f --target PARTIALS.csv [--gofr G.csv] [--moves 5000] [--sigma 0.2]
                                    [--min-dist "A-A:3.0,A-B:2.2"] [--max-move 0.05] [--rmax 8] [--dr 0.02] [--seed 0] [--outdir OUT]
    python scripts/rmclite.py --selftest
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import math
import os
import sys
from dataclasses import dataclass, field

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rmcprofile_tools as rt  # noqa: E402

KB_EV = 8.617333262e-5          # Boltzmann constant, eV/K


# ----------------------------------------------------------------------------
# the box
# ----------------------------------------------------------------------------
@dataclass
class Box:
    types: list
    counts: list
    lattice: np.ndarray
    frac: np.ndarray
    atoms: np.ndarray
    density: float

    @classmethod
    def from_rmc6f(cls, cfg):
        return cls(list(cfg.atom_types), list(cfg.counts), np.array(cfg.lattice, float),
                   np.array(cfg.frac, float) % 1.0, np.array(cfg.atoms, dtype=object), float(cfg.density))

    @property
    def n(self):
        return int(self.frac.shape[0])

    def cart(self):
        return self.frac @ self.lattice

    def distance_row(self, i, frac_i=None):
        """Minimum-image distances from atom i (at frac_i if given) to every atom; entry i = inf."""
        fi = self.frac[i] if frac_i is None else frac_i
        d = self.frac - fi
        d -= np.round(d)
        row = np.sqrt(((d @ self.lattice) ** 2).sum(axis=1))
        row[i] = np.inf
        return row

    def to_rmc6f(self, template):
        n = self.n
        return rt.Rmc6f(header=dict(template.header), atom_types=list(self.types), counts=list(self.counts),
                        cell=template.cell, lattice=self.lattice.copy(), supercell=template.supercell,
                        density=self.density, atoms=self.atoms.copy(), frac=self.frac.copy(),
                        site=np.array(template.site, int) if len(template.site) == n else np.zeros(n, int),
                        cellidx=(np.array(template.cellidx, int) if len(template.cellidx) == n
                                 else np.zeros((n, 3), int)),
                        banner=["(Version 6f format configuration file)", "(Generated by rmclite %s)" % rt.__version__])


def rms_displacement(box, ref):
    d = box.frac - ref.frac
    d -= np.round(d)
    return float(np.sqrt(((d @ box.lattice) ** 2).sum(axis=1).mean()))


# ----------------------------------------------------------------------------
# incremental partial histograms on RMCProfile's grid
# ----------------------------------------------------------------------------
class Histogram:
    def __init__(self, box, rmax, dr):
        L = min(np.linalg.norm(box.lattice, axis=1))
        if rmax > L / 2 + 1e-9:
            raise ValueError("rmax %.2f exceeds half the shortest cell edge (%.2f)" % (rmax, L / 2))
        self.box, self.rmax, self.dr = box, rmax, dr
        self.r, self.edges = rt.rmc_grid(rmax, dr)
        self.labels = rt.pair_labels(box.types)
        self.tindex = {t: k for k, t in enumerate(box.types)}
        self.atype = np.array([self.tindex[a] for a in box.atoms])
        self.pair_of = {}
        for i, a in enumerate(box.types):
            for j, b in enumerate(box.types):
                self.pair_of[(i, j)] = "%s-%s" % ((a, b) if i <= j else (b, a))
        V = abs(np.linalg.det(box.lattice))
        self.norm = {}
        for i, a in enumerate(box.types):
            for b in box.types[i:]:
                na, nb = box.counts[i], box.counts[box.types.index(b)]
                self.norm["%s-%s" % (a, b)] = 1.0 / (na * (nb / V) * 4 * np.pi * self.r ** 2 * dr)
        self.rebuild()

    def _bin_rows(self, i, row):
        """Histogram one atom's distance row into per-pair bin counts (pairs seen from i's side)."""
        out = {}
        mask = np.isfinite(row) & (row < self.edges[-1])
        bins = np.searchsorted(self.edges, row[mask], side="right") - 1
        ok = (bins >= 0) & (bins < len(self.r))
        bins, types = bins[ok], self.atype[mask][ok]
        ti = self.atype[i]
        for tj in range(len(self.box.types)):
            sel = types == tj
            if sel.any():
                lab = self.pair_of[(ti, tj)]
                out[lab] = out.get(lab, 0) + np.bincount(bins[sel], minlength=len(self.r))
        return out

    @staticmethod
    def _factor(lab):
        """partial_gr histograms the full n_a x n_b distance block: an unlike pair (a,b) is
        counted once (row a, column b), a like pair twice (both orderings). Summing every
        atom's row counts every pair twice, so unlike counts are halved on rebuild and a
        move touches a like pair's bins by 2 and an unlike pair's by 1."""
        a, b = lab.split("-")
        return 2 if a == b else 1

    def rebuild(self):
        self.counts = {lab: np.zeros(len(self.r), dtype=np.int64) for lab in self.labels}
        for i in range(self.box.n):
            for lab, c in self._bin_rows(i, self.box.distance_row(i)).items():
                self.counts[lab] += c
        for lab in self.labels:
            if self._factor(lab) == 1:
                self.counts[lab] //= 2

    def update(self, i, old_row, new_row):
        for lab, c in self._bin_rows(i, old_row).items():
            self.counts[lab] -= self._factor(lab) * c
        for lab, c in self._bin_rows(i, new_row).items():
            self.counts[lab] += self._factor(lab) * c

    def g(self, counts=None):
        counts = self.counts if counts is None else counts
        return {lab: counts[lab] * self.norm[lab] for lab in self.labels}


# ----------------------------------------------------------------------------
# targets (chi^2 terms) and constraints
# ----------------------------------------------------------------------------
class PartialTarget:
    def __init__(self, label, r, g, sigma):
        self.label, self.r, self.g, self.sigma = label, np.asarray(r, float), np.asarray(g, float), float(sigma)

    def chi2(self, hist, counts=None):
        assert np.allclose(hist.r, self.r), "target grid must equal the histogram grid"
        calc = hist.g(counts)[self.label]
        return float(np.sum((calc - self.g) ** 2) / self.sigma ** 2)


class TotalGTarget:
    def __init__(self, r, G, sigma, weights):
        self.r, self.G, self.sigma, self.w = np.asarray(r, float), np.asarray(G, float), float(sigma), dict(weights)

    def calc(self, hist, counts=None):
        g = hist.g(counts)
        return sum(self.w[lab] * (g[lab] - 1.0) for lab in g)

    def chi2(self, hist, counts=None):
        assert np.allclose(hist.r, self.r), "target grid must equal the histogram grid"
        return float(np.sum((self.calc(hist, counts) - self.G) ** 2) / self.sigma ** 2)


class FqTarget(TotalGTarget):
    def __init__(self, q, F, sigma, density, weights):
        self.q, self.F, self.sigma = np.asarray(q, float), np.asarray(F, float), float(sigma)
        self.density, self.w = float(density), dict(weights)

    def chi2(self, hist, counts=None):
        G = TotalGTarget.calc(self, hist, counts)
        Fc = rt.fq_from_gr(hist.r, G, self.density, self.q)
        return float(np.sum((Fc - self.F) ** 2) / self.sigma ** 2)


class ClosestApproach:
    def __init__(self, dmin):
        self.dmin = dict(dmin)

    def ok(self, hist, i, new_row):
        ti = hist.atype[i]
        for tj in range(len(hist.box.types)):
            lab = hist.pair_of[(ti, tj)]
            if lab in self.dmin:
                sel = hist.atype == tj
                if np.any(new_row[sel] < self.dmin[lab]):
                    return False
        return True


class DistanceWindow:
    """Pairs whose starting distance lies inside [rmin, rmax] for their label must stay inside."""

    def __init__(self, windows):
        self.windows = dict(windows)
        self.members = None                     # {i: [j, ...]} fixed at first use

    def _init(self, hist):
        self.members = {}
        for i in range(hist.box.n):
            row = hist.box.distance_row(i)
            for j in np.where(np.isfinite(row))[0]:
                lab = hist.pair_of[(hist.atype[i], hist.atype[j])]
                if lab in self.windows and self.windows[lab][0] <= row[j] <= self.windows[lab][1]:
                    self.members.setdefault(i, []).append(int(j))

    def ok(self, hist, i, new_row):
        if self.members is None:
            self._init(hist)
        for j in self.members.get(i, ()):
            lab = hist.pair_of[(hist.atype[i], hist.atype[j])]
            lo, hi = self.windows[lab]
            if not (lo <= new_row[j] <= hi):
                return False
        return True


class BondPotential:
    """Harmonic bond energy  U = sum 1/2 k (d - r0)^2  over pairs of `label` closer than `cutoff`,
    entering the acceptance rule as U / (k_B T)."""

    def __init__(self, label, k, r0, cutoff, T):
        self.label, self.k, self.r0, self.cutoff, self.T = label, float(k), float(r0), float(cutoff), float(T)

    def energy_row(self, hist, i, row):
        ti = hist.atype[i]
        e = 0.0
        for tj in range(len(hist.box.types)):
            if hist.pair_of[(ti, tj)] == self.label:
                d = row[(hist.atype == tj) & np.isfinite(row)]
                d = d[d < self.cutoff]
                e += 0.5 * self.k * np.sum((d - self.r0) ** 2)
        return e / (KB_EV * self.T)


# ----------------------------------------------------------------------------
# the engine
# ----------------------------------------------------------------------------
@dataclass
class RunState:
    generated: int = 0
    tested: int = 0
    accepted: int = 0
    chi2_history: list = field(default_factory=list)


class RmcLite:
    def __init__(self, box, rmax, dr, targets, constraints=(), potentials=(), max_move=None, seed=0):
        self.box = box
        self.hist = Histogram(box, rmax, dr)
        self.targets = list(targets)
        self.constraints = list(constraints)
        self.potentials = list(potentials)
        self.max_move = dict(max_move or {t: 0.05 for t in box.types})
        self.rng = np.random.default_rng(seed)
        self.inv_lattice = np.linalg.inv(box.lattice)
        self.chi2 = self._chi2(self.hist.counts)
        self.state = RunState(chi2_history=[(0, self.chi2)])

    def _chi2(self, counts):
        return sum(t.chi2(self.hist, counts) for t in self.targets)

    def step(self):
        """One move: returns True if accepted."""
        st = self.state
        st.generated += 1
        i = int(self.rng.integers(self.box.n))
        amp = self.max_move[self.box.atoms[i]]
        v = self.rng.normal(size=3)
        v *= amp * self.rng.random() / np.linalg.norm(v)
        new_frac = (self.box.frac[i] + v @ self.inv_lattice) % 1.0
        old_row = self.box.distance_row(i)
        new_row = self.box.distance_row(i, new_frac)
        if not all(c.ok(self.hist, i, new_row) for c in self.constraints):
            return False
        st.tested += 1
        trial = {lab: c.copy() for lab, c in self.hist.counts.items()}
        f = self.hist._factor
        for lab, c in self.hist._bin_rows(i, old_row).items():
            trial[lab] -= f(lab) * c
        for lab, c in self.hist._bin_rows(i, new_row).items():
            trial[lab] += f(lab) * c
        chi2_new = self._chi2(trial)
        delta = 0.5 * (chi2_new - self.chi2)
        for p in self.potentials:
            delta += p.energy_row(self.hist, i, new_row) - p.energy_row(self.hist, i, old_row)
        if delta > 0 and self.rng.random() >= math.exp(-delta):
            return False
        self.box.frac[i] = new_frac
        self.hist.counts = trial
        self.chi2 = chi2_new
        st.accepted += 1
        return True

    def run(self, n_moves, print_every=0, callback=None):
        for k in range(n_moves):
            self.step()
            if print_every and (k + 1) % print_every == 0:
                self.state.chi2_history.append((self.state.generated, self.chi2))
                print("moves %d tested %d accepted %d chi2 %.6g"
                      % (self.state.generated, self.state.tested, self.state.accepted, self.chi2))
                if callback:
                    callback(self)
        self.state.chi2_history.append((self.state.generated, self.chi2))
        return self.state


def synth_targets(box, rmax, dr, noise, rng):
    """Partials and Keen G(r) of `box` on RMCProfile's grid, plus Gaussian noise of s.d. `noise` on each partial."""
    h = Histogram(box, rmax, dr)
    parts = {lab: g + (rng.normal(0.0, noise, g.shape) if noise else 0.0) for lab, g in h.g().items()}
    cfg = rt.Rmc6f(atom_types=list(box.types), counts=list(box.counts))
    w = rt.neutron_weights(cfg)
    G = sum(w[lab] * (parts[lab] - 1.0) for lab in parts)
    return h.r, parts, G


# ----------------------------------------------------------------------------
# CLI (rule 11), audit log (rule 12), selftest
# ----------------------------------------------------------------------------
def parse_min_dist(text):
    out = {}
    for item in text.split(","):
        item = item.strip()
        if item:
            lab, val = item.split(":")
            out[lab.strip()] = float(val)
    return out


def _write_partials_csv(path, r, parts):
    labels = list(parts)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("   r (Ang), " + ", ".join("%9s" % lab for lab in labels) + "\n")
        for k in range(len(r)):
            f.write("%10.5f , " % r[k] + " , ".join("%.9f" % parts[lab][k] for lab in labels) + " , \n")


def _write_gofr_csv(path, r, G):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("r (Ang), G(r) barn, G(r) barn\n")
        for k in range(len(r)):
            f.write("%12.6f , %16.9f , %16.9f\n" % (r[k], G[k], G[k]))


def _audit(log_dir, argv, ok, extra):
    os.makedirs(log_dir, exist_ok=True)
    stamp = _dt.datetime.now().strftime("%Y%m%dT%H%M%S%f")
    with open(os.path.join(log_dir, "rmclite_%s.json" % stamp), "w", encoding="utf-8") as f:
        json.dump({"tool": "rmclite", "version": rt.__version__, "argv": list(argv), "ok": bool(ok), **extra}, f, indent=2)


def _nacl_box(n=2, a=5.64):
    base = {"Na": [(0, 0, 0), (.5, .5, 0), (.5, 0, .5), (0, .5, .5)],
            "Cl": [(.5, 0, 0), (0, .5, 0), (0, 0, .5), (.5, .5, .5)]}
    atoms, frac = [], []
    for el in ("Na", "Cl"):
        for i, j, k in np.ndindex(n, n, n):
            for x, y, z in base[el]:
                atoms.append(el)
                frac.append([(x + i) / n, (y + j) / n, (z + k) / n])
    N = len(atoms)
    return Box(["Na", "Cl"], [N // 2, N // 2], n * a * np.eye(3), np.array(frac), np.array(atoms, dtype=object), N / (n * a) ** 3)


def selftest(outdir):
    """From the ideal 2x2x2 rock-salt lattice toward the partials of a thermally
    displaced copy (s.d. 0.05 A): chi2 must fall by 80 % in 2000 moves."""
    os.makedirs(outdir, exist_ok=True)
    rng = np.random.default_rng(1)
    truth = _nacl_box(2)
    truth.frac = (truth.frac + rng.normal(0, 0.05, truth.frac.shape) / 11.28) % 1.0
    r, parts, _ = synth_targets(truth, 5.0, 0.02, 0.0, rng)
    start = _nacl_box(2)
    eng = RmcLite(start, 5.0, 0.02, [PartialTarget(lab, r, parts[lab], 0.2) for lab in parts],
                  constraints=[ClosestApproach({"Na-Na": 3.0, "Na-Cl": 2.2, "Cl-Cl": 3.0})],
                  max_move={"Na": 0.05, "Cl": 0.05}, seed=3)
    chi0 = eng.chi2
    eng.run(2000)
    return [{"name": "synthetic recovery (2x2x2 NaCl, 2000 moves)", "ok": eng.chi2 < 0.2 * chi0,
             "detail": "chi2 %.3g -> %.3g" % (chi0, eng.chi2)}]


def build_parser():
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--outdir", default="out", help="where outputs are written")
    common.add_argument("--log-dir", default="logs", help="where the JSON audit log is written")
    common.add_argument("-q", "--quiet", action="store_true", help="print only the verdict")
    common.add_argument("--rmax", type=float, default=8.0, help="largest r of the partials (below half the shortest cell edge)")
    common.add_argument("--dr", type=float, default=0.02, help="r step (Angstrom); RMCProfile's grid r_k = k*dr")
    common.add_argument("--seed", type=int, default=0, help="random seed")
    ap = argparse.ArgumentParser(prog="rmclite", description=__doc__.splitlines()[0], parents=[common])
    ap.add_argument("--version", action="version", version="rmcprofile-skill %s" % rt.__version__)
    ap.add_argument("--selftest", action="store_true", help="synthetic recovery on a small rock-salt box, exit 0/1")
    sub = ap.add_subparsers(dest="cmd")
    s = sub.add_parser("synth", help="displace a configuration and write target partials / G(r) of the original", parents=[common])
    s.add_argument("rmc6f")
    s.add_argument("--displace", type=float, default=0.15, help="Gaussian displacement s.d. (Angstrom) applied to every atom")
    s.add_argument("--noise", type=float, default=0.0, help="Gaussian noise s.d. added to each target partial")
    f = sub.add_parser("fit", help="run rmclite on a configuration against target partials (and optionally G(r))", parents=[common])
    f.add_argument("rmc6f")
    f.add_argument("--target", required=True, help="target _PDFpartials.csv (RMCProfile layout)")
    f.add_argument("--gofr", default=None, help="optional target G(r) CSV (r, G, G) in barn")
    f.add_argument("--moves", type=int, default=5000, help="moves to generate")
    f.add_argument("--sigma", type=float, default=0.2, help="sigma of every partial target (and of G(r) if given)")
    f.add_argument("--min-dist", default="", help="closest approach per pair, e.g. \"Na-Na:3.0,Na-Cl:2.2\"")
    f.add_argument("--max-move", type=float, default=0.05, help="largest displacement per move (Angstrom), all types")
    f.add_argument("--print-every", type=int, default=0, help="print chi2 every N moves (0 = only at the end)")
    return ap


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    args = build_parser().parse_args(argv)
    if args.selftest:
        checks = selftest(args.outdir)
        ok = all(c["ok"] for c in checks)
        if not args.quiet:
            for c in checks:
                print("[%s] %s - %s" % ("PASS" if c["ok"] else "FAIL", c["name"], c["detail"]))
        _audit(args.log_dir, argv, ok, {"checks": checks})
        print("rmclite selftest: %s" % ("ALL CHECKS PASSED" if ok else "FAILED"))
        return 0 if ok else 1
    if args.cmd not in ("synth", "fit"):
        build_parser().print_help()
        return 2
    os.makedirs(args.outdir, exist_ok=True)
    cfg = rt.read_rmc6f(args.rmc6f)
    stem = os.path.splitext(os.path.basename(args.rmc6f))[0]
    rng = np.random.default_rng(args.seed)
    if args.cmd == "synth":
        ideal = Box.from_rmc6f(cfg)
        r, parts, G = synth_targets(ideal, args.rmax, args.dr, args.noise, rng)
        moved = Box.from_rmc6f(cfg)
        moved.frac = (moved.frac + rng.normal(0.0, args.displace, moved.frac.shape) @ np.linalg.inv(moved.lattice)) % 1.0
        moved.to_rmc6f(cfg).write(os.path.join(args.outdir, stem + "_displaced.rmc6f"))
        _write_partials_csv(os.path.join(args.outdir, stem + "_target_PDFpartials.csv"), r, parts)
        _write_gofr_csv(os.path.join(args.outdir, stem + "_target_GofR.csv"), r, G)
        rms = rms_displacement(moved, ideal)
        if not args.quiet:
            print("synth %s: %d atoms displaced (rms %.3f A), targets on %d r points -> %s" % (stem, moved.n, rms, len(r), args.outdir))
        _audit(args.log_dir, argv, True, {"rms_displacement": rms, "n_r": len(r)})
        return 0
    box = Box.from_rmc6f(cfg)
    r_t, parts_t = rt.read_partials_csv(args.target)
    targets = [PartialTarget(lab, r_t, parts_t[lab], args.sigma) for lab in parts_t]
    if args.gofr:
        r_g, G_t, _ = rt.read_csv_pair(args.gofr)
        targets.append(TotalGTarget(r_g, G_t, args.sigma, rt.neutron_weights(cfg)))
    constraints = [ClosestApproach(parse_min_dist(args.min_dist))] if args.min_dist else []
    rmax = r_t[-1] + 1e-9                         # the target grid fixes the histogram grid
    eng = RmcLite(box, rmax, float(np.round(np.diff(r_t).mean(), 6)), targets, constraints,
                  max_move={t: args.max_move for t in box.types}, seed=args.seed)
    chi0 = eng.chi2
    st = eng.run(args.moves, print_every=args.print_every)
    fit_stem = stem + "_fit"
    eng.box.to_rmc6f(cfg).write(os.path.join(args.outdir, fit_stem + ".rmc6f"))
    with open(os.path.join(args.outdir, fit_stem + ".chi2"), "w", encoding="utf-8", newline="\n") as f:
        f.write("m_accepted   m_generated   m_tested   chi2\n")
        for gen, chi in st.chi2_history:
            f.write(" %d   %d   %d   %.6g\n" % (st.accepted if gen == st.generated else 0, gen, st.tested if gen == st.generated else 0, chi))
    g = eng.hist.g()
    _write_partials_csv(os.path.join(args.outdir, fit_stem + "_PDFpartials.csv"), eng.hist.r, g)
    w = rt.neutron_weights(cfg)
    _write_gofr_csv(os.path.join(args.outdir, fit_stem + "_GofR.csv"), eng.hist.r, sum(w[lab] * (g[lab] - 1.0) for lab in g))
    if not args.quiet:
        print("fit %s: %d generated, %d tested, %d accepted, chi2 %.4g -> %.4g -> %s"
              % (stem, st.generated, st.tested, st.accepted, chi0, eng.chi2, args.outdir))
    _audit(args.log_dir, argv, True, {"chi2_start": chi0, "chi2_end": eng.chi2, "generated": st.generated, "accepted": st.accepted})
    return 0


if __name__ == "__main__":
    sys.exit(main())
