# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Fabio Campolim
"""rmcprofile-skill toolkit: RMCProfile 6.7.9 file formats, input-set checker,
package runner and configuration analysis.

Formats follow the RMCProfile manual v6.7.9 (rmcprofile.ornl.gov/manual/):
§4.1 the .dat control file, §4.11 the .rmc6f configuration, §4.12 experimental
data files, §4.13 Bragg files, §3.4 output files. Nothing here is taken from the
package itself; the package is only *run*, through RMCPROFILE_HOME.

Usage (CLI):
    python scripts/rmcprofile_tools.py --version
    python scripts/rmcprofile_tools.py --selftest [--outdir OUT] [--log-dir LOGS]
    python scripts/rmcprofile_tools.py check  STEM [--dir DIR]
    python scripts/rmcprofile_tools.py run    STEM [--dir DIR] [--home HOME] [--timeout MIN]
    python scripts/rmcprofile_tools.py pdf    FILE.rmc6f [--rmax 20] [--dr 0.02] [--outdir OUT]
    python scripts/rmcprofile_tools.py coord  FILE.rmc6f --pair A B --rmax R
    python scripts/rmcprofile_tools.py angles FILE.rmc6f --triplet A B C --rmax R
"""

from __future__ import annotations

import datetime as _dt
import os
import re
from dataclasses import dataclass, field

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
_VERSION_FILE = os.path.join(HERE, "..", "VERSION")
with open(_VERSION_FILE, encoding="utf-8") as _f:
    __version__ = _f.read().strip()

BARN_PER_FM2 = 0.01          # 1 barn = 100 fm^2


# ----------------------------------------------------------------------------
# .rmc6f  (manual §4.11)
# ----------------------------------------------------------------------------
@dataclass
class Rmc6f:
    header: dict = field(default_factory=dict)      # "Key" -> "value" for every "Key: value" line
    atom_types: list = field(default_factory=list)
    counts: list = field(default_factory=list)
    cell: tuple = (0.0, 0.0, 0.0, 90.0, 90.0, 90.0)
    lattice: np.ndarray = field(default_factory=lambda: np.eye(3))
    supercell: tuple = (1, 1, 1)
    density: float = 0.0
    atoms: np.ndarray = field(default_factory=lambda: np.array([], dtype=object))
    frac: np.ndarray = field(default_factory=lambda: np.zeros((0, 3)))
    site: np.ndarray = field(default_factory=lambda: np.zeros(0, dtype=int))
    cellidx: np.ndarray = field(default_factory=lambda: np.zeros((0, 3), dtype=int))
    banner: list = field(default_factory=list)      # the leading "(...)" lines, kept verbatim

    def n_atoms(self):
        return int(self.frac.shape[0])

    def cart(self):
        """Cartesian positions in Å: rows of `frac` times the lattice matrix (rows = vectors)."""
        return self.frac @ self.lattice

    def concentrations(self):
        n = self.n_atoms()
        return {t: c / n for t, c in zip(self.atom_types, self.counts)}

    def write(self, path):
        h = self.header
        lines = list(self.banner) or ["(Version 6f format configuration file)",
                                      "(Generated by rmcprofile-skill %s)" % __version__]
        lines += [
            "Metadata date:        %s" % h.get("Metadata date", _dt.date.today().strftime("%d-%m-%Y")),
            "Number of types of atoms:   %d" % len(self.atom_types),
            "Atom types present:         %s" % " ".join(self.atom_types),
            "Number of each atom type:   %s" % " ".join(str(c) for c in self.counts),
            "Number of moves generated:           %s" % h.get("Number of moves generated", "0"),
            "Number of moves tried:               %s" % h.get("Number of moves tried", "0"),
            "Number of moves accepted:            %s" % h.get("Number of moves accepted", "0"),
            "Number of prior configuration saves: %s" % h.get("Number of prior configuration saves", "0"),
            "Number of atoms:                     %d" % self.n_atoms(),
            "Supercell dimensions:                %d %d %d" % tuple(self.supercell),
            "Number density (Ang^-3):                 %.6f" % self.density,
            "Cell (Ang/deg):  %11.6f %11.6f %11.6f %11.6f %11.6f %11.6f" % tuple(self.cell),
            "Lattice vectors (Ang):",
        ]
        lines += ["%12.6f%12.6f%12.6f" % tuple(row) for row in self.lattice]
        lines.append("Atoms:")
        for i in range(self.n_atoms()):
            x, y, z = self.frac[i]
            a, b, c = self.cellidx[i]
            lines.append("%d %-4s %11.6f %11.6f %11.6f %d %d %d %d"
                         % (i + 1, self.atoms[i], x, y, z, self.site[i], a, b, c))
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(lines) + "\n")


_HEADER_KEYS = ("Number of types of atoms", "Atom types present", "Number of each atom type",
                "Number of atoms", "Supercell dimensions", "Number density (Ang^-3)", "Cell (Ang/deg)")


def read_rmc6f(path):
    """Parse a version-6f configuration. Raises ValueError on an inconsistent header."""
    cfg = Rmc6f()
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = f.read().splitlines()          # handles LF and CRLF alike
    i = 0
    while i < len(lines) and lines[i].strip() != "Atoms:":
        ln = lines[i].rstrip()
        if ln.startswith("("):
            cfg.banner.append(ln)
        elif ln.strip() == "Lattice vectors (Ang):":
            cfg.lattice = np.array([[float(v) for v in lines[i + k + 1].split()] for k in range(3)])
            i += 3
        elif ":" in ln:
            key, _, val = ln.partition(":")
            cfg.header[key.strip()] = val.strip()
        i += 1
    if i >= len(lines):
        raise ValueError("%s: no 'Atoms:' line" % path)
    h = cfg.header
    missing = [k for k in _HEADER_KEYS if k not in h]
    if missing:
        raise ValueError("%s: header lacks %s" % (path, missing))
    cfg.atom_types = h["Atom types present"].split()
    cfg.counts = [int(v) for v in h["Number of each atom type"].split()]
    cfg.supercell = tuple(int(v) for v in h["Supercell dimensions"].split())
    cfg.density = float(h["Number density (Ang^-3)"])
    cfg.cell = tuple(float(v) for v in h["Cell (Ang/deg)"].split())
    n_declared = int(h["Number of atoms"])
    rows = [ln.split() for ln in lines[i + 1:] if ln.strip()]
    if len(rows) != n_declared:
        raise ValueError("%s: 'Number of atoms' says %d, file has %d atom lines" % (path, n_declared, len(rows)))
    if sum(cfg.counts) != n_declared:
        raise ValueError("%s: 'Number of each atom type' sums to %d, not %d" % (path, sum(cfg.counts), n_declared))
    cfg.atoms = np.array([r[1] for r in rows], dtype=object)
    cfg.frac = np.array([[float(r[2]), float(r[3]), float(r[4])] for r in rows])
    cfg.site = (np.array([int(r[5]) for r in rows]) if all(len(r) >= 6 for r in rows)
                else np.zeros(len(rows), dtype=int))
    cfg.cellidx = (np.array([[int(r[6]), int(r[7]), int(r[8])] for r in rows])
                   if all(len(r) >= 9 for r in rows) else np.zeros((len(rows), 3), dtype=int))
    return cfg


# ----------------------------------------------------------------------------
# .dat control file  (manual §4.1)
# ----------------------------------------------------------------------------
@dataclass
class DatBlock:
    name: str
    arg: str = ""
    items: list = field(default_factory=list)       # [(KEY, value_string), ...] ; flags carry ""

    def get(self, key, default=None):
        for k, v in self.items:
            if k == key:
                return v
        return default


@dataclass
class DatFile:
    scalars: dict = field(default_factory=dict)     # KEY -> value string, file order preserved
    atoms: list = field(default_factory=list)
    blocks: list = field(default_factory=list)
    order: list = field(default_factory=list)       # ("scalar", KEY) | ("atoms",) | ("block", index)

    def get(self, block_name, key, default=None):
        for b in self.blocks:
            if b.name == block_name:
                return b.get(key, default)
        return default

    def set(self, block_name, key, value):
        for b in self.blocks:
            if b.name == block_name:
                for i, (k, _) in enumerate(b.items):
                    if k == key:
                        b.items[i] = (key, value)
                        return
                b.items.append((key, value))
                return
        raise KeyError(block_name)

    def data_blocks(self):
        """The experimental-data blocks: *_DATA and EXAFS."""
        return [b for b in self.blocks if b.name.endswith("_DATA") or b.name == "EXAFS"]

    def filenames(self):
        return [v for b in self.blocks for k, v in b.items if k == "FILENAME"]

    def minimum_distances(self):
        return [float(v) for v in self.scalars.get("MINIMUM_DISTANCES", "").split() if _is_number(v)]

    def time_limit_minutes(self):
        v = self.scalars.get("TIME_LIMIT", "0 MINUTES").split()
        return float(v[0]) if v else 0.0

    def write(self, path):
        out = []
        for entry in self.order:
            if entry[0] == "scalar":
                out.append("%s :: %s" % (entry[1], self.scalars[entry[1]]) if self.scalars[entry[1]]
                           else "%s ::" % entry[1])
            elif entry[0] == "atoms":
                out.append("")
                out.append("ATOMS :: %s" % " ".join(self.atoms))
                out.append("")
            else:
                b = self.blocks[entry[1]]
                out.append("")
                out.append("%s :: %s" % (b.name, b.arg) if b.arg else "%s ::" % b.name)
                for k, v in b.items:
                    out.append("  > %s :: %s" % (k, v) if v else "  > %s" % k)
        out += ["", "END ::"]
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(out) + "\n")


_NUM = re.compile(r"^[-+]?(\d+\.?\d*|\.\d+)([eEdD][-+]?\d+)?$")

_BLOCK_KEYWORDS = {"FLAGS", "BRAGG", "POTENTIALS", "BVS", "DISTANCE_WINDOW", "POLYHEDRAL_RESTRAINT",
                   "FIXED_COORDINATION_CONSTRAINTS", "AVERAGE_COORDINATION_CONSTRAINTS", "MAGNETIC",
                   "EXAFS", "ATOM_SWAP", "NANO_SIZE", "RESOLUTION", "WEIGHT_OPTIMIZATION"}
_SCALAR_KEYWORDS = {"TITLE", "MATERIAL", "PHASE", "TEMPERATURE", "PRESSURE", "INVESTIGATOR", "DATA_NOTE",
                    "RMC_NOTE", "NUMBER_DENSITY", "MINIMUM_DISTANCES", "MAXIMUM_MOVES", "R_SPACING",
                    "PRINT_PERIOD", "TIME_LIMIT", "SAVE_PERIOD", "INPUT_CONFIGURATION_FORMAT",
                    "SAVE_CONFIGURATION_FORMAT", "IGNORE_HISTORY_FILE", "SEED", "BOX_SIZE"}


def _is_number(tok):
    return bool(_NUM.match(tok))


def _strip_comment(s):
    return s.split("%%", 1)[0].rstrip()


def _opens_block(key, val):
    """A line 'KEY :: <int or nothing>' with an upper-case key that is not a known scalar
    opens a block; *_DATA, FLAGS and the known block keywords always do."""
    if key.endswith("_DATA") or key in _BLOCK_KEYWORDS:
        return True
    if key in _SCALAR_KEYWORDS:
        return False
    return key.isupper() and (val == "" or val.isdigit())


def read_dat(path):
    """Parse a version-6 .dat file. Raises ValueError when 'END ::' is missing."""
    d = DatFile()
    with open(path, encoding="utf-8", errors="replace") as f:
        raw = f.read().splitlines()
    current = None
    saw_end = False
    for ln in raw:
        s = _strip_comment(ln.strip())
        if not s:
            continue
        if s.startswith(">"):
            if current is None:
                raise ValueError("%s: item line outside a block: %r" % (path, ln))
            body = s[1:].strip()
            key, sep, val = body.partition("::")
            current.items.append((key.strip(), val.strip() if sep else ""))
            continue
        key, sep, val = s.partition("::")
        if not sep:
            raise ValueError("%s: unrecognised line %r" % (path, ln))
        key, val = key.strip(), val.strip()
        if key == "END":
            saw_end = True
            current = None
            break
        if key == "ATOMS":
            d.atoms = val.split()
            d.order.append(("atoms",))
            current = None
        elif _opens_block(key, val):
            current = DatBlock(name=key, arg=val)
            d.blocks.append(current)
            d.order.append(("block", len(d.blocks) - 1))
        else:
            d.scalars[key] = val
            d.order.append(("scalar", key))
            current = None
    if not saw_end:
        raise ValueError("%s: no 'END ::' line" % path)
    return d


# ----------------------------------------------------------------------------
# experimental data files  (manual §4.12) and the Bragg family (§4.13), .dw (§2.5)
# ----------------------------------------------------------------------------
@dataclass
class DataFile:
    x: np.ndarray
    y: np.ndarray
    err: np.ndarray | None = None
    title: str = ""
    metadata: dict = field(default_factory=dict)


def _to_float(tok):
    return float(tok.replace("D", "E").replace("d", "e"))


def read_data_file(path):
    """Two-line header ('<npoints>' then a title line, then columns) or STOG
    ('# Key: value' lines, then columns). Two columns -> (x, y); three -> (x, y, err)."""
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = f.read().splitlines()
    meta, title, rows = {}, "", []
    if lines and lines[0].lstrip().startswith("#"):
        i = 0
        while i < len(lines) and lines[i].lstrip().startswith("#"):
            body = lines[i].lstrip("#").strip()
            if ":" in body and not body.startswith("-"):
                k, _, v = body.partition(":")
                meta[k.strip()] = v.strip()
            i += 1
        title = meta.get("Title", "")
        data_lines = lines[i:]
    else:
        n = int(lines[0].split()[0])
        title = lines[1].rstrip()
        data_lines = lines[2:]
        if sum(1 for ln in data_lines if ln.strip()) < n:
            raise ValueError("%s: header says %d points, fewer data lines follow" % (path, n))
    for ln in data_lines:
        toks = ln.split()
        if toks and _is_number(toks[0]):
            rows.append([_to_float(t) for t in toks])
    arr = np.array(rows)
    if arr.ndim != 2 or arr.shape[1] < 2:
        raise ValueError("%s: expected at least two numeric columns" % path)
    return DataFile(arr[:, 0], arr[:, 1], arr[:, 2] if arr.shape[1] >= 3 else None, title, meta)


def write_data_file(path, x, y, title, err=None, style="two-line"):
    x, y = np.asarray(x, float), np.asarray(y, float)
    cols = [x, y] + ([np.asarray(err, float)] if err is not None else [])
    body = ["  " + "  ".join("%.8f" % c[i] for c in cols) for i in range(len(x))]
    if style == "two-line":
        head = [" %d" % len(x), title]
    elif style == "stog":
        head = ["# File: rmcprofile-skill data file", "# Title: %s" % title, "# Number of points: %d" % len(x),
                "# ------------------------------------"]
    else:
        raise ValueError("style must be 'two-line' or 'stog'")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(head + body) + "\n")


@dataclass
class Bragg:
    npoints: int
    bank: int
    scale: float
    volume: float
    title: str
    x: np.ndarray
    y: np.ndarray


def read_bragg(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = f.read().splitlines()
    n, bank, scale, vol = lines[0].split()[:4]
    n, bank = int(n), int(bank)
    rows = [[_to_float(t) for t in ln.split()[:2]] for ln in lines[2:] if ln.strip() and _is_number(ln.split()[0])]
    if len(rows) != n:
        raise ValueError("%s: header says %d points, file has %d" % (path, n, len(rows)))
    arr = np.array(rows)
    return Bragg(n, bank, _to_float(scale), _to_float(vol), lines[1].strip(), arr[:, 0], arr[:, 1])


def read_back(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        toks = f.read().split()
    n = int(toks[0])
    vals = np.array([_to_float(t) for t in toks[1:1 + n]])
    if len(vals) != n:
        raise ValueError("%s: expected %d background coefficients" % (path, n))
    return vals


def read_inst(path):
    """GSAS instrument-parameter extract: '<nbanks>' then, per bank, its number on
    its own line followed by the value lines until the next bank number."""
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = [ln for ln in f.read().splitlines() if ln.strip()]
    nb = int(lines[0].split()[0])
    banks, cur = [], None
    for ln in lines[1:]:
        toks = ln.split()
        if len(toks) == 1 and toks[0].isdigit():
            cur = {"bank": int(toks[0]), "values": []}
            banks.append(cur)
        elif cur is not None:
            cur["values"].extend(_to_float(t) for t in toks)
    if len(banks) != nb:
        raise ValueError("%s: header says %d banks, found %d" % (path, nb, len(banks)))
    return banks


def read_hkl(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = [ln.split() for ln in f.read().splitlines() if ln.strip()]
    return {"scale": _to_float(lines[0][0]),
            "ranges": [(int(a), int(b), _to_float(c)) for a, b, c in (ln[:3] for ln in lines[1:4])]}


def read_dw(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return [(int(t[0]), _to_float(t[1]), _to_float(t[2]))
                for t in (ln.split() for ln in f.read().splitlines()) if len(t) >= 3]


# ----------------------------------------------------------------------------
# output files  (manual §3.4)
# ----------------------------------------------------------------------------
def read_chi2_history(path):
    """'<stem>.chi2' / '<stem>_chi2.txt': a header line of column names, then rows."""
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = [ln for ln in f.read().splitlines() if ln.strip()]
    names = lines[0].split()
    rows = [[_to_float(t) for t in ln.split()] for ln in lines[1:] if _is_number(ln.split()[0])]
    arr = np.array(rows) if rows else np.zeros((0, len(names)))
    out = {}
    for j, nm in enumerate(names):
        col = arr[:, j] if arr.size else np.zeros(0)
        out[nm] = col.astype(int) if nm.startswith("m_") or nm == "moves" else col
    return out


def _read_csv_numeric(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = f.read().splitlines()
    header = [h.strip() for h in lines[0].split(",") if h.strip()]
    rows = []
    for ln in lines[1:]:
        toks = [t.strip() for t in ln.split(",") if t.strip()]
        if toks and _is_number(toks[0]):
            rows.append([_to_float(t) for t in toks])
    return header, np.array(rows)


def read_csv_pair(path):
    """_SQn.csv / _PDFn.csv / _bragg.csv -> (x, calculated, experiment)."""
    _, arr = _read_csv_numeric(path)
    return arr[:, 0], arr[:, 1], arr[:, 2]


def read_partials_csv(path):
    """_PDFpartials.csv / _SQnpartials.csv -> (x, {pair_label: values})."""
    header, arr = _read_csv_numeric(path)
    labels = header[1:]
    return arr[:, 0], {lab: arr[:, 1 + j] for j, lab in enumerate(labels)}
