# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Fabio Campolim
"""rmcprofile-skill toolkit: RMCProfile 6.7.9 file formats, input-set checker,
package runner and configuration analysis.

Formats follow the RMCProfile manual v6.7.9 (rmcprofile.ornl.gov/manual/):
§4.1 the .dat control file, §4.11 the .rmc6f configuration, §4.12 experimental
data files, §4.13 Bragg files, §3.4 output files. Nothing here is taken from the
package itself; the package is only *run*, through RMCPROFILE_HOME.

Usage (CLI):
    python scripts/rmcprofile_tools.py --version
    python scripts/rmcprofile_tools.py --selftest [--outdir OUT] [--log-dir LOGS]
    python scripts/rmcprofile_tools.py check  STEM [--dir DIR]
    python scripts/rmcprofile_tools.py run    STEM [--dir DIR] [--home HOME] [--timeout MIN]
    python scripts/rmcprofile_tools.py pdf    FILE.rmc6f [--rmax 20] [--dr 0.02] [--outdir OUT]
    python scripts/rmcprofile_tools.py coord  FILE.rmc6f --pair A B --rmax R
    python scripts/rmcprofile_tools.py angles FILE.rmc6f --triplet A B C --rmax R
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import re
import subprocess
import sys
import time
from dataclasses import dataclass, field

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
_VERSION_FILE = os.path.join(HERE, "..", "VERSION")
with open(_VERSION_FILE, encoding="utf-8") as _f:
    __version__ = _f.read().strip()

BARN_PER_FM2 = 0.01          # 1 barn = 100 fm^2


# ----------------------------------------------------------------------------
# .rmc6f  (manual §4.11)
# ----------------------------------------------------------------------------
@dataclass
class Rmc6f:
    header: dict = field(default_factory=dict)      # "Key" -> "value" for every "Key: value" line
    atom_types: list = field(default_factory=list)
    counts: list = field(default_factory=list)
    cell: tuple = (0.0, 0.0, 0.0, 90.0, 90.0, 90.0)
    lattice: np.ndarray = field(default_factory=lambda: np.eye(3))
    supercell: tuple = (1, 1, 1)
    density: float = 0.0
    atoms: np.ndarray = field(default_factory=lambda: np.array([], dtype=object))
    frac: np.ndarray = field(default_factory=lambda: np.zeros((0, 3)))
    site: np.ndarray = field(default_factory=lambda: np.zeros(0, dtype=int))
    cellidx: np.ndarray = field(default_factory=lambda: np.zeros((0, 3), dtype=int))
    banner: list = field(default_factory=list)      # the leading "(...)" lines, kept verbatim

    def n_atoms(self):
        return int(self.frac.shape[0])

    def cart(self):
        """Cartesian positions in Å: rows of `frac` times the lattice matrix (rows = vectors)."""
        return self.frac @ self.lattice

    def concentrations(self):
        n = self.n_atoms()
        return {t: c / n for t, c in zip(self.atom_types, self.counts)}

    def write(self, path):
        h = self.header
        lines = list(self.banner) or ["(Version 6f format configuration file)",
                                      "(Generated by rmcprofile-skill %s)" % __version__]
        lines += [
            "Metadata date:        %s" % h.get("Metadata date", _dt.date.today().strftime("%d-%m-%Y")),
            "Number of types of atoms:   %d" % len(self.atom_types),
            "Atom types present:         %s" % " ".join(self.atom_types),
            "Number of each atom type:   %s" % " ".join(str(c) for c in self.counts),
            "Number of moves generated:           %s" % h.get("Number of moves generated", "0"),
            "Number of moves tried:               %s" % h.get("Number of moves tried", "0"),
            "Number of moves accepted:            %s" % h.get("Number of moves accepted", "0"),
            "Number of prior configuration saves: %s" % h.get("Number of prior configuration saves", "0"),
            "Number of atoms:                     %d" % self.n_atoms(),
            "Supercell dimensions:                %d %d %d" % tuple(self.supercell),
            "Number density (Ang^-3):                 %.6f" % self.density,
            "Cell (Ang/deg):  %11.6f %11.6f %11.6f %11.6f %11.6f %11.6f" % tuple(self.cell),
            "Lattice vectors (Ang):",
        ]
        lines += ["%12.6f%12.6f%12.6f" % tuple(row) for row in self.lattice]
        lines.append("Atoms:")
        for i in range(self.n_atoms()):
            x, y, z = self.frac[i]
            a, b, c = self.cellidx[i]
            lines.append("%d %-4s %11.6f %11.6f %11.6f %d %d %d %d"
                         % (i + 1, self.atoms[i], x, y, z, self.site[i], a, b, c))
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(lines) + "\n")


_HEADER_KEYS = ("Number of types of atoms", "Atom types present", "Number of each atom type",
                "Number of atoms", "Supercell dimensions", "Number density (Ang^-3)", "Cell (Ang/deg)")


def read_rmc6f(path):
    """Parse a version-6f configuration. Raises ValueError on an inconsistent header."""
    cfg = Rmc6f()
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = f.read().splitlines()          # handles LF and CRLF alike
    i = 0
    while i < len(lines) and lines[i].strip() != "Atoms:":
        ln = lines[i].rstrip()
        if ln.startswith("("):
            cfg.banner.append(ln)
        elif ln.strip() == "Lattice vectors (Ang):":
            cfg.lattice = np.array([[float(v) for v in lines[i + k + 1].split()] for k in range(3)])
            i += 3
        elif ":" in ln:
            key, _, val = ln.partition(":")
            cfg.header[key.strip()] = val.strip()
        i += 1
    if i >= len(lines):
        raise ValueError("%s: no 'Atoms:' line" % path)
    h = cfg.header
    missing = [k for k in _HEADER_KEYS if k not in h]
    if missing:
        raise ValueError("%s: header lacks %s" % (path, missing))
    cfg.atom_types = h["Atom types present"].split()
    cfg.counts = [int(v) for v in h["Number of each atom type"].split()]
    cfg.supercell = tuple(int(v) for v in h["Supercell dimensions"].split())
    cfg.density = float(h["Number density (Ang^-3)"])
    cfg.cell = tuple(float(v) for v in h["Cell (Ang/deg)"].split())
    n_declared = int(h["Number of atoms"])
    # atom lines: "index label x y z [site ia ib ic]" (data2config) or
    # "index label [1] x y z" (written by RMCProfile itself; the bracketed token is a flag we skip)
    rows = [[t for t in ln.split() if not t.startswith("[")] for ln in lines[i + 1:] if ln.strip()]
    if len(rows) != n_declared:
        raise ValueError("%s: 'Number of atoms' says %d, file has %d atom lines" % (path, n_declared, len(rows)))
    if sum(cfg.counts) != n_declared:
        raise ValueError("%s: 'Number of each atom type' sums to %d, not %d" % (path, sum(cfg.counts), n_declared))
    cfg.atoms = np.array([r[1] for r in rows], dtype=object)
    cfg.frac = np.array([[float(r[2]), float(r[3]), float(r[4])] for r in rows])
    cfg.site = (np.array([int(r[5]) for r in rows]) if all(len(r) >= 6 for r in rows)
                else np.zeros(len(rows), dtype=int))
    cfg.cellidx = (np.array([[int(r[6]), int(r[7]), int(r[8])] for r in rows])
                   if all(len(r) >= 9 for r in rows) else np.zeros((len(rows), 3), dtype=int))
    return cfg


# ----------------------------------------------------------------------------
# .dat control file  (manual §4.1)
# ----------------------------------------------------------------------------
@dataclass
class DatBlock:
    name: str
    arg: str = ""
    items: list = field(default_factory=list)       # [(KEY, value_string), ...] ; flags carry ""

    def get(self, key, default=None):
        for k, v in self.items:
            if k == key:
                return v
        return default


@dataclass
class DatFile:
    scalars: dict = field(default_factory=dict)     # KEY -> value string, file order preserved
    atoms: list = field(default_factory=list)
    blocks: list = field(default_factory=list)
    order: list = field(default_factory=list)       # ("scalar", KEY) | ("atoms",) | ("block", index)

    def get(self, block_name, key, default=None):
        for b in self.blocks:
            if b.name == block_name:
                return b.get(key, default)
        return default

    def set(self, block_name, key, value):
        for b in self.blocks:
            if b.name == block_name:
                for i, (k, _) in enumerate(b.items):
                    if k == key:
                        b.items[i] = (key, value)
                        return
                b.items.append((key, value))
                return
        raise KeyError(block_name)

    def data_blocks(self):
        """The experimental-data blocks: *_DATA and EXAFS."""
        return [b for b in self.blocks if b.name.endswith("_DATA") or b.name == "EXAFS"]

    def filenames(self):
        return [v for b in self.blocks for k, v in b.items if k == "FILENAME"]

    def minimum_distances(self):
        return [float(v) for v in self.scalars.get("MINIMUM_DISTANCES", "").split() if _is_number(v)]

    def time_limit_minutes(self):
        v = self.scalars.get("TIME_LIMIT", "0 MINUTES").split()
        return float(v[0]) if v else 0.0

    def write(self, path):
        out = []
        for entry in self.order:
            if entry[0] == "scalar":
                out.append("%s :: %s" % (entry[1], self.scalars[entry[1]]) if self.scalars[entry[1]]
                           else "%s ::" % entry[1])
            elif entry[0] == "atoms":
                out.append("")
                out.append("ATOMS :: %s" % " ".join(self.atoms))
                out.append("")
            else:
                b = self.blocks[entry[1]]
                out.append("")
                out.append("%s :: %s" % (b.name, b.arg) if b.arg else "%s ::" % b.name)
                for k, v in b.items:
                    out.append("  > %s" % k if v is None else ("  > %s ::" % k if v == "" else "  > %s :: %s" % (k, v)))
        out += ["", "END ::"]
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(out) + "\n")


_NUM = re.compile(r"^[-+]?(\d+\.?\d*|\.\d+)([eEdD][-+]?\d+)?$")

_BLOCK_KEYWORDS = {"FLAGS", "BRAGG", "POTENTIALS", "BVS", "DISTANCE_WINDOW", "POLYHEDRAL_RESTRAINT",
                   "FIXED_COORDINATION_CONSTRAINTS", "AVERAGE_COORDINATION_CONSTRAINTS", "MAGNETIC",
                   "EXAFS", "ATOM_SWAP", "NANO_SIZE", "RESOLUTION", "WEIGHT_OPTIMIZATION"}
_SCALAR_KEYWORDS = {"TITLE", "MATERIAL", "PHASE", "TEMPERATURE", "PRESSURE", "INVESTIGATOR", "DATA_NOTE",
                    "RMC_NOTE", "NUMBER_DENSITY", "MINIMUM_DISTANCES", "MAXIMUM_MOVES", "R_SPACING",
                    "PRINT_PERIOD", "TIME_LIMIT", "SAVE_PERIOD", "INPUT_CONFIGURATION_FORMAT",
                    "SAVE_CONFIGURATION_FORMAT", "IGNORE_HISTORY_FILE", "SEED", "BOX_SIZE"}


def _is_number(tok):
    return bool(_NUM.match(tok))


def _strip_comment(s):
    return s.split("%%", 1)[0].rstrip()


def _opens_block(key, val):
    """A line 'KEY :: <int or nothing>' with an upper-case key that is not a known scalar
    opens a block; *_DATA, FLAGS and the known block keywords always do."""
    if key.endswith("_DATA") or key in _BLOCK_KEYWORDS:
        return True
    if key in _SCALAR_KEYWORDS:
        return False
    return key.isupper() and (val == "" or val.isdigit())


def read_dat(path):
    """Parse a version-6 .dat file. Raises ValueError when 'END ::' is missing."""
    d = DatFile()
    with open(path, encoding="utf-8", errors="replace") as f:
        raw = f.read().splitlines()
    current = None
    saw_end = False
    for ln in raw:
        s = _strip_comment(ln.strip())
        if not s:
            continue
        if s.startswith(">"):
            if current is None:
                raise ValueError("%s: item line outside a block: %r" % (path, ln))
            body = s[1:].strip()
            key, sep, val = body.partition("::")
            # '> KEY :: value' -> value; '> KEY ::' (e.g. CONVOLVE ::) -> ""; '> KEY' (e.g. NO_MOVEOUT) -> None.
            # The distinction is kept because RMCProfile's own files write CONVOLVE with '::' and the
            # NO_* flags without; the writer reproduces each form.
            current.items.append((key.strip(), val.strip() if sep else None))
            continue
        key, sep, val = s.partition("::")
        if not sep:
            raise ValueError("%s: unrecognised line %r" % (path, ln))
        key, val = key.strip(), val.strip()
        if key == "END":
            saw_end = True
            current = None
            break
        if key == "ATOMS":
            d.atoms = val.split()
            d.order.append(("atoms",))
            current = None
        elif _opens_block(key, val):
            current = DatBlock(name=key, arg=val)
            d.blocks.append(current)
            d.order.append(("block", len(d.blocks) - 1))
        else:
            d.scalars[key] = val
            d.order.append(("scalar", key))
            current = None
    if not saw_end:
        raise ValueError("%s: no 'END ::' line" % path)
    return d


# ----------------------------------------------------------------------------
# experimental data files  (manual §4.12) and the Bragg family (§4.13), .dw (§2.5)
# ----------------------------------------------------------------------------
@dataclass
class DataFile:
    x: np.ndarray
    y: np.ndarray
    err: np.ndarray | None = None
    title: str = ""
    metadata: dict = field(default_factory=dict)


def _to_float(tok):
    return float(tok.replace("D", "E").replace("d", "e"))


def read_data_file(path):
    """Two-line header ('<npoints>' then a title line, then columns) or STOG
    ('# Key: value' lines, then columns). Two columns -> (x, y); three -> (x, y, err)."""
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = f.read().splitlines()
    meta, title, rows = {}, "", []
    if lines and lines[0].lstrip().startswith("#"):
        i = 0
        while i < len(lines) and lines[i].lstrip().startswith("#"):
            body = lines[i].lstrip("#").strip()
            if ":" in body and not body.startswith("-"):
                k, _, v = body.partition(":")
                meta[k.strip()] = v.strip()
            i += 1
        title = meta.get("Title", "")
        data_lines = lines[i:]
    else:
        n = int(lines[0].split()[0])
        title = lines[1].rstrip()
        data_lines = lines[2:]
        if sum(1 for ln in data_lines if ln.strip()) < n:
            raise ValueError("%s: header says %d points, fewer data lines follow" % (path, n))
    for ln in data_lines:
        toks = ln.split()
        if toks and _is_number(toks[0]):
            rows.append([_to_float(t) for t in toks])
    arr = np.array(rows)
    if arr.ndim != 2 or arr.shape[1] < 2:
        raise ValueError("%s: expected at least two numeric columns" % path)
    return DataFile(arr[:, 0], arr[:, 1], arr[:, 2] if arr.shape[1] >= 3 else None, title, meta)


def write_data_file(path, x, y, title, err=None, style="two-line"):
    x, y = np.asarray(x, float), np.asarray(y, float)
    cols = [x, y] + ([np.asarray(err, float)] if err is not None else [])
    body = ["  " + "  ".join("%.8f" % c[i] for c in cols) for i in range(len(x))]
    if style == "two-line":
        head = [" %d" % len(x), title]
    elif style == "stog":
        head = ["# File: rmcprofile-skill data file", "# Title: %s" % title, "# Number of points: %d" % len(x),
                "# ------------------------------------"]
    else:
        raise ValueError("style must be 'two-line' or 'stog'")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(head + body) + "\n")


@dataclass
class Bragg:
    npoints: int
    bank: int
    scale: float
    volume: float
    title: str
    x: np.ndarray
    y: np.ndarray


def read_bragg(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = f.read().splitlines()
    n, bank, scale, vol = lines[0].split()[:4]
    n, bank = int(n), int(bank)
    rows = [[_to_float(t) for t in ln.split()[:2]] for ln in lines[2:] if ln.strip() and _is_number(ln.split()[0])]
    if len(rows) < n:
        raise ValueError("%s: header says %d points, file has %d" % (path, n, len(rows)))
    arr = np.array(rows[:n])           # RMCProfile reads exactly npoints rows; the package ships files with a few more
    return Bragg(n, bank, _to_float(scale), _to_float(vol), lines[1].strip(), arr[:, 0], arr[:, 1])


def read_back(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        toks = f.read().split()
    n = int(toks[0])
    vals = np.array([_to_float(t) for t in toks[1:1 + n]])
    if len(vals) != n:
        raise ValueError("%s: expected %d background coefficients" % (path, n))
    return vals


def read_inst(path):
    """GSAS instrument-parameter extract: '<nbanks>' then, per bank, its number on
    its own line followed by the value lines until the next bank number."""
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = [ln for ln in f.read().splitlines() if ln.strip()]
    nb = int(lines[0].split()[0])
    banks, cur = [], None
    for ln in lines[1:]:
        toks = ln.split()
        if len(toks) == 1 and toks[0].isdigit():
            cur = {"bank": int(toks[0]), "values": []}
            banks.append(cur)
        elif cur is not None:
            cur["values"].extend(_to_float(t) for t in toks)
    if len(banks) != nb:
        raise ValueError("%s: header says %d banks, found %d" % (path, nb, len(banks)))
    return banks


def read_hkl(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = [ln.split() for ln in f.read().splitlines() if ln.strip()]
    return {"scale": _to_float(lines[0][0]),
            "ranges": [(int(a), int(b), _to_float(c)) for a, b, c in (ln[:3] for ln in lines[1:4])]}


def read_dw(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return [(int(t[0]), _to_float(t[1]), _to_float(t[2]))
                for t in (ln.split() for ln in f.read().splitlines()) if len(t) >= 3]


# ----------------------------------------------------------------------------
# output files  (manual §3.4)
# ----------------------------------------------------------------------------
def read_chi2_history(path):
    """'<stem>.chi2' / '<stem>_chi2.txt': a header line of column names, then rows."""
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = [ln for ln in f.read().splitlines() if ln.strip()]
    names = lines[0].split()
    rows = [[_to_float(t) for t in ln.split()] for ln in lines[1:] if _is_number(ln.split()[0])]
    arr = np.array(rows) if rows else np.zeros((0, len(names)))
    out = {}
    for j, nm in enumerate(names):
        col = arr[:, j] if arr.size else np.zeros(0)
        out[nm] = col.astype(int) if nm.startswith("m_") or nm == "moves" else col
    return out


def _read_csv_numeric(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = f.read().splitlines()
    header = [h.strip() for h in lines[0].split(",") if h.strip()]
    rows = []
    for ln in lines[1:]:
        toks = [t.strip() for t in ln.split(",") if t.strip()]
        if toks and _is_number(toks[0]):
            rows.append([_to_float(t) for t in toks])
    return header, np.array(rows)


def read_csv_pair(path):
    """_SQn.csv / _PDFn.csv / _bragg.csv -> (x, calculated, experiment)."""
    _, arr = _read_csv_numeric(path)
    return arr[:, 0], arr[:, 1], arr[:, 2]


def read_partials_csv(path):
    """_PDFpartials.csv / _SQnpartials.csv -> (x, {pair_label: values})."""
    header, arr = _read_csv_numeric(path)
    labels = header[1:]
    return arr[:, 0], {lab: arr[:, 1 + j] for j, lab in enumerate(labels)}


# ----------------------------------------------------------------------------
# input-set checker  (manual §3.2 checklist, §4.1, §5.6.1)
# ----------------------------------------------------------------------------
@dataclass
class Finding:
    level: str          # ERROR | WARN | INFO
    code: str
    message: str


def check_input_set(stem, directory):
    """Check every file RMCProfile will open for `stem` in `directory`."""
    d = str(directory)
    out = []
    dat_path = os.path.join(d, stem + ".dat")
    if not os.path.isfile(dat_path):
        return [Finding("ERROR", "no-dat", "%s.dat not found in %s" % (stem, d))]
    try:
        dat = read_dat(dat_path)
    except ValueError as e:
        return [Finding("ERROR", "dat-parse", str(e))]

    # configuration: .his6f is used in preference to .rmc6f unless IGNORE_HISTORY_FILE (§3.2)
    his, rmc = os.path.join(d, stem + ".his6f"), os.path.join(d, stem + ".rmc6f")
    cfg = None
    if os.path.isfile(his) and "IGNORE_HISTORY_FILE" not in dat.scalars:
        out.append(Finding("WARN", "history-file", "%s.his6f present: it will be used instead of the .rmc6f; a history "
                           "file left by a zero-move pass makes the run compute an empty PDF and crawl — delete it or add "
                           "IGNORE_HISTORY_FILE ::" % stem))
    if os.path.isfile(rmc):
        try:
            cfg = read_rmc6f(rmc)
        except ValueError as e:
            out.append(Finding("ERROR", "rmc6f-parse", str(e)))
    elif not os.path.isfile(his) and not os.path.isfile(os.path.join(d, stem + ".cfg")):
        out.append(Finding("ERROR", "no-configuration", "no %s.rmc6f, .his6f or .cfg" % stem))

    # atom order must agree between ATOMS :: and the configuration header (§4.1)
    if cfg is not None and dat.atoms and cfg.atom_types != dat.atoms:
        out.append(Finding("ERROR", "atom-order", "ATOMS :: %s but the configuration lists %s (same order required)"
                           % (" ".join(dat.atoms), " ".join(cfg.atom_types))))

    # MINIMUM_DISTANCES has one value per pair, pairs ordered AA AB AC BB BC CC (§4.1)
    n = len(dat.atoms)
    npairs = n * (n + 1) // 2
    md = dat.minimum_distances()
    if n and len(md) != npairs:
        out.append(Finding("ERROR", "minimum-distances-count",
                           "MINIMUM_DISTANCES has %d values, %d atom types need %d" % (len(md), n, npairs)))
    mm = [float(v) for v in dat.scalars.get("MAXIMUM_MOVES", "").split() if _is_number(v)]
    if n and mm and len(mm) != n:
        out.append(Finding("ERROR", "maximum-moves-count", "MAXIMUM_MOVES has %d values for %d atom types" % (len(mm), n)))

    # every data block names a file that exists and whose END_POINT is within the data
    for b in dat.data_blocks():
        fn = b.get("FILENAME")
        if not fn:
            out.append(Finding("ERROR", "data-block-no-filename", "%s has no FILENAME" % b.name))
            continue
        fp = os.path.join(d, fn)
        if not os.path.isfile(fp):
            out.append(Finding("ERROR", "data-file-missing", "%s: %s not found" % (b.name, fn)))
            continue
        if fn not in os.listdir(d):
            # exists only case-insensitively (Windows): the same set stops on Linux/macOS
            # with "does not exist! Hence we have to stop" and exit code 0 (GaPO4 exercise, 2026-09-05)
            out.append(Finding("WARN", "filename-case",
                               "%s: %s is named with different letter case on disk; RMCProfile on Linux/macOS will not find it"
                               % (b.name, fn)))
        if b.name == "EXAFS":
            continue                                  # chi(k) files have their own layout (later plan)
        try:
            df = read_data_file(fp)
        except (ValueError, IndexError) as e:
            out.append(Finding("ERROR", "data-file-parse", "%s: %s" % (fn, e)))
            continue
        end = b.get("END_POINT")
        if end and end.isdigit() and int(end) > len(df.x):
            out.append(Finding("WARN", "end-point-beyond-data",
                               "%s: END_POINT %s but %s has %d points (RMCProfile clamps to the data; the package's own smoke test does this)"
                               % (b.name, end, fn, len(df.x))))
        if b.get("WEIGHT") is None:
            out.append(Finding("WARN", "no-weight", "%s: no WEIGHT (the manual's examples always set one)" % b.name))

    # Bragg block needs .bragg + .inst (+ .back); hkl either as file or in the .dat (§4.13)
    if any(b.name == "BRAGG" for b in dat.blocks):
        for ext, code in ((".bragg", "bragg-file-missing"), (".inst", "bragg-inst-missing"), (".back", "bragg-back-missing")):
            if not os.path.isfile(os.path.join(d, stem + ext)):
                out.append(Finding("ERROR", code, "BRAGG :: block but %s%s is missing" % (stem, ext)))
        bp = os.path.join(d, stem + ".bragg")
        if os.path.isfile(bp):
            try:
                read_bragg(bp)
            except (ValueError, IndexError) as e:
                out.append(Finding("ERROR", "bragg-parse", str(e)))
        if not os.path.isfile(os.path.join(d, stem + ".hkl")) and dat.get("BRAGG", "SUPERCELL") is None:
            out.append(Finding("WARN", "hkl-range-unspecified", "no %s.hkl and no SUPERCELL :: in the BRAGG block" % stem))

    # polyhedral restraint: the program waits forever for a missing .poly (audit 2026-09-05)
    if any(b.name == "POLYHEDRAL_RESTRAINT" for b in dat.blocks) and not os.path.isfile(os.path.join(d, stem + ".poly")):
        out.append(Finding("ERROR", "poly-file-missing",
                           "POLYHEDRAL_RESTRAINT :: block but %s.poly is missing (RMCProfile waits for it indefinitely)" % stem))

    # nanoparticle mode needs the bulk density beside the radius (chapter 7, 2026-09-05)
    if "PARTICLE_RADIUS" in dat.scalars and "BULK_RHO" not in dat.scalars:
        out.append(Finding("ERROR", "bulk-rho-missing",
                           "PARTICLE_RADIUS :: without BULK_RHO :: (RMCProfile stops: \"Low dimension RMC requested. But no 'BULK_RHO' keyword found\")"))

    # neighbour files must be deleted after a configuration change (§5.6.1)
    for ext in (".neigh", ".neighlist"):
        if os.path.isfile(os.path.join(d, stem + ext)):
            out.append(Finding("WARN", "stale-neighbour-files", "%s%s present: delete it if the configuration changed" % (stem, ext)))

    # potentials: bonds/triplets are regenerated if absent (§3.2) — info only
    if any(b.name == "POTENTIALS" for b in dat.blocks):
        for ext in (".bonds", ".triplets"):
            if not os.path.isfile(os.path.join(d, stem + ext)):
                out.append(Finding("INFO", "potential-lists-regenerated", "%s%s absent: RMCProfile will generate it" % (stem, ext)))

    nerr = sum(1 for f in out if f.level == "ERROR")
    out.append(Finding("INFO", "summary", "%s: %d data block(s), %d atom type(s), %d error(s)"
                       % (stem, len(dat.data_blocks()), n, nerr)))
    return out


# ----------------------------------------------------------------------------
# package locator and runner  (references/package.md — the setup scripts' contract)
# ----------------------------------------------------------------------------
@dataclass
class Package:
    home: str
    platform: str        # "windows" | "linux"
    binary: str
    version_hint: str = ""


def find_package(home=None):
    """RMCProfile_package directory from `home` or $RMCPROFILE_HOME; None if absent."""
    home = home or os.environ.get("RMCPROFILE_HOME")
    if not home or not os.path.isdir(os.path.join(home, "exe")):
        return None
    win = os.path.join(home, "exe", "rmcprofile.exe")
    lin = os.path.join(home, "exe", "rmcprofile")
    if os.path.isfile(win):
        return Package(home, "windows", win, _version_hint(home))
    if os.path.isfile(lin):
        return Package(home, "linux", lin, _version_hint(home))
    return None


def _version_hint(home):
    """The version the package's own setup script announces (Linux: 'Welcome to RMCProfile version X')."""
    p = os.path.join(home, "exe", "setup_cmds")
    if os.path.isfile(p):
        with open(p, encoding="utf-8", errors="replace") as f:
            m = re.search(r"version\s+([\d.]+)", f.read())
            if m:
                return m.group(1)
    return ""


def package_env(pkg):
    env = dict(os.environ)
    exe = os.path.join(pkg.home, "exe")
    if pkg.platform == "windows":
        env["RMCPROFILE_DIR"] = pkg.home
        env["PATH"] = os.pathsep.join([exe, os.path.join(exe, "cygwin_libs"), os.path.join(exe, "cuda_lib"), env.get("PATH", "")])
    else:
        libs = os.path.join(exe, "libs")
        env.update({"RMCProfile_PATH": pkg.home, "PGPLOT_DIR": libs, "LD_LIBRARY_PATH": libs, "LIBRARY_PATH": libs})
        env["PATH"] = os.pathsep.join([env.get("PATH", ""), exe])
    return env


@dataclass
class RunResult:
    returncode: int | None
    seconds: float
    log_path: str
    outputs: list
    final_chi2: dict | None


def run_rmcprofile(stem, directory, pkg, timeout_min=None, log_name="run.log"):
    """Run `rmcprofile <stem>` in `directory` with the package environment.
    Stdout+stderr go to `log_name`; `outputs` lists files created or modified by
    the run; `final_chi2` is the last row of <stem>.chi2 / <stem>_chi2.txt if
    present. A timeout kills the process and returns returncode None."""
    d = str(directory)
    before = {f: os.path.getmtime(os.path.join(d, f)) for f in os.listdir(d)}
    log_path = os.path.join(d, log_name)
    t0 = time.time()
    with open(log_path, "w", encoding="utf-8", errors="replace") as log:
        try:
            proc = subprocess.run([pkg.binary, stem], cwd=d, env=package_env(pkg), stdout=log, stderr=subprocess.STDOUT,
                                  timeout=timeout_min * 60 if timeout_min else None)
            rc = proc.returncode
        except subprocess.TimeoutExpired:
            rc = None
    secs = time.time() - t0
    outputs = sorted(f for f in os.listdir(d)
                     if f != log_name and (f not in before or os.path.getmtime(os.path.join(d, f)) > before[f]))
    final = None
    for cand in (stem + ".chi2", stem + "_chi2.txt"):
        p = os.path.join(d, cand)
        if os.path.isfile(p):
            hist = read_chi2_history(p)
            if hist and len(next(iter(hist.values()))):
                final = {k: (int(v[-1]) if v.dtype.kind == "i" else float(v[-1])) for k, v in hist.items()}
            break
    return RunResult(rc, secs, log_path, outputs, final)


# ----------------------------------------------------------------------------
# configuration analysis  (references/method.md — Keen 2001 definitions)
# ----------------------------------------------------------------------------
# Bound coherent neutron scattering lengths, fm (Sears, Neutron News 3 (1992) 26;
# NIST table https://www.ncnr.nist.gov/resources/n-lengths/). Natural abundance;
# D = deuterium. Extend as needed.
NEUTRON_B = {
    "H": -3.7390, "D": 6.671, "Li": -1.90, "Be": 7.79, "B": 5.30, "C": 6.6460, "N": 9.36, "O": 5.803, "F": 5.654,
    "Na": 3.63, "Mg": 5.375, "Al": 3.449, "Si": 4.1491, "P": 5.13, "S": 2.847, "Cl": 9.5770, "K": 3.67, "Ca": 4.70,
    "Sc": 12.29, "Ti": -3.438, "V": -0.3824, "Cr": 3.635, "Mn": -3.73, "Fe": 9.45, "Co": 2.49, "Ni": 10.3, "Cu": 7.718,
    "Zn": 5.680, "Ga": 7.288, "Ge": 8.185, "As": 6.58, "Se": 7.970, "Br": 6.795, "Rb": 7.09, "Sr": 7.02, "Y": 7.75,
    "Zr": 7.16, "Nb": 7.054, "Mo": 6.715, "Ag": 5.922, "Cd": 4.87, "In": 4.065, "Sn": 6.225, "Sb": 5.57, "Te": 5.80,
    "I": 5.28, "Cs": 5.42, "Ba": 5.07, "La": 8.24, "Ce": 4.84, "Nd": 7.69, "Gd": 6.5, "Hf": 7.7, "Ta": 6.91, "W": 4.86,
    "Pt": 9.60, "Au": 7.63, "Hg": 12.692, "Tl": 8.776, "Pb": 9.405, "Bi": 8.532, "Th": 10.31, "U": 8.417,
}


def pair_labels(types):
    """AA AB AC BB BC CC ... — the manual's partial order (§4.1 MINIMUM_DISTANCES, §3.4 partials)."""
    return ["%s-%s" % (types[i], types[j]) for i in range(len(types)) for j in range(i, len(types))]


def _min_image_distances(cfg):
    """All-pairs minimum-image distances (N x N, diagonal = inf); general cell."""
    frac = cfg.frac - np.floor(cfg.frac)
    d = frac[:, None, :] - frac[None, :, :]
    d -= np.round(d)
    cart = d @ cfg.lattice
    r = np.sqrt((cart ** 2).sum(-1))
    np.fill_diagonal(r, np.inf)
    return r


def rmc_grid(rmax, dr):
    """RMCProfile's r grid: r_k = k*dr (k >= 1) up to rmax, bins centred on r_k."""
    n = int(np.floor(rmax / dr + 1e-9))
    r = dr * np.arange(1, n + 1)
    edges = np.concatenate([[max(0.0, r[0] - dr / 2)], r + dr / 2])
    return r, edges


def partial_gr(cfg, rmax=20.0, dr=0.02, grid="rmcprofile"):
    """Partial pair distribution functions g_ij(r) by histogram, normalised to 1 at large r.
    grid="rmcprofile": r_k = k*dr with bins centred on r_k (equals RMCProfile's _PDFpartials.csv);
    grid="centre": bins [k dr, (k+1) dr) labelled by their centre. Minimum image only: rmax must
    be below half the shortest cell edge."""
    L = min(np.linalg.norm(cfg.lattice, axis=1))
    if rmax > L / 2 + 1e-9:
        raise ValueError("rmax %.2f exceeds half the shortest cell edge (%.2f): enlarge the supercell" % (rmax, L / 2))
    if grid == "rmcprofile":
        r, edges = rmc_grid(rmax, dr)
    elif grid == "centre":
        r = np.arange(dr / 2, rmax, dr)
        edges = np.arange(0.0, rmax + dr, dr)[: len(r) + 1]
    else:
        raise ValueError("grid must be 'rmcprofile' or 'centre'")
    dist = _min_image_distances(cfg)
    V = abs(np.linalg.det(cfg.lattice))
    types = cfg.atom_types
    idx = {t: np.where(cfg.atoms == t)[0] for t in types}
    out = {}
    shell = 4 * np.pi * r ** 2 * dr
    for i, a in enumerate(types):
        for b in types[i:]:
            block = dist[np.ix_(idx[a], idx[b])]
            h, _ = np.histogram(block[np.isfinite(block)], bins=edges)
            n_a, n_b = len(idx[a]), len(idx[b])
            out["%s-%s" % (a, b)] = h / (n_a * (n_b / V) * shell)
    return r, out


def neutron_weights(cfg, radiation="neutron"):
    """w_ij = c_i c_j b_i b_j (x2 for i != j) in barn; the coefficients of Keen's G(r)."""
    if radiation != "neutron":
        raise NotImplementedError("X-ray weights (Q-dependent form factors) arrive with the X-ray chapter")
    n = float(sum(cfg.counts))
    c = {t: k / n for t, k in zip(cfg.atom_types, cfg.counts)}
    w = {}
    for i, a in enumerate(cfg.atom_types):
        for b in cfg.atom_types[i:]:
            mult = 1.0 if a == b else 2.0
            w["%s-%s" % (a, b)] = mult * c[a] * c[b] * NEUTRON_B[a] * NEUTRON_B[b] * BARN_PER_FM2
    return w


def total_gr(r, partials, cfg, radiation="neutron"):
    """Keen 2001 eq. 10: G(r) = sum_ij c_i c_j b_i b_j (g_ij(r) - 1), in barn. Returns (r, G)."""
    w = neutron_weights(cfg, radiation)
    G = np.zeros(len(r))
    for lab in partials:
        G += w[lab] * (partials[lab] - 1.0)
    return np.asarray(r, float), G


def fq_from_gr(r, G, density, q):
    """Keen 2001 eq. 12: F(Q) = rho0 * int 4 pi r^2 G(r) sin(Qr)/(Qr) dr (barn)."""
    r = np.asarray(r, float)
    G = np.asarray(G, float)
    q = np.asarray(q, float)
    dr = np.diff(r).mean()
    qr = np.outer(q, r)
    safe = np.where(qr == 0, 1.0, qr)
    kernel = np.where(qr == 0, 1.0, np.sin(qr) / safe)
    return density * (kernel * (4 * np.pi * r ** 2 * G * dr)).sum(axis=1)


def coordination(cfg, a, b, rmax):
    """Number of B atoms within rmax of every A atom; returns (per-A counts, histogram)."""
    dist = _min_image_distances(cfg)
    ia, ib = np.where(cfg.atoms == a)[0], np.where(cfg.atoms == b)[0]
    counts = (dist[np.ix_(ia, ib)] <= rmax).sum(axis=1)
    hist = {int(k): int(v) for k, v in zip(*np.unique(counts, return_counts=True))}
    return counts, hist


def bond_angles(cfg, a, b, c, rmax):
    """B-A-C angles (degrees) for every A with B and C neighbours within rmax (minimum image)."""
    frac = cfg.frac - np.floor(cfg.frac)
    ia, ib, ic = (np.where(cfg.atoms == t)[0] for t in (a, b, c))
    out = []
    for i in ia:
        def vecs(js):
            d = frac[js] - frac[i]
            d -= np.round(d)
            v = d @ cfg.lattice
            keep = (np.linalg.norm(v, axis=1) <= rmax) & (js != i)
            return v[keep], js[keep]
        vb, jb = vecs(ib)
        vc, jc = vecs(ic)
        for p in range(len(jb)):
            for s in range(len(jc)):
                if b == c and jc[s] <= jb[p]:
                    continue                      # each unordered pair once
                if jb[p] == jc[s]:
                    continue
                cosang = np.dot(vb[p], vc[s]) / (np.linalg.norm(vb[p]) * np.linalg.norm(vc[s]))
                out.append(np.degrees(np.arccos(np.clip(cosang, -1.0, 1.0))))
    return np.array(out)


def average_cell(cfg):
    a, b, c, al, be, ga = cfg.cell
    na, nb, nc = cfg.supercell
    return (a / na, b / nb, c / nc, al, be, ga)


def _analysis_main(args, argv):
    cfg = read_rmc6f(args.rmc6f)
    stem = os.path.splitext(os.path.basename(args.rmc6f))[0]
    os.makedirs(args.outdir, exist_ok=True)
    extra = {"rmc6f": args.rmc6f, "n_atoms": cfg.n_atoms()}
    if args.cmd == "pdf":
        r, parts = partial_gr(cfg, args.rmax, args.dr, grid=args.grid)
        _, G = total_gr(r, parts, cfg, args.radiation)
        q = np.arange(args.dq, args.qmax, args.dq)
        F = fq_from_gr(r, G, cfg.density, q)
        labels = list(parts)
        with open(os.path.join(args.outdir, stem + "_PDFpartials.csv"), "w", encoding="utf-8", newline="\n") as f:
            f.write("   r (Ang), " + ", ".join("%9s" % lab for lab in labels) + "\n")
            for k in range(len(r)):
                f.write("%10.5f , " % r[k] + " , ".join("%.9f" % parts[lab][k] for lab in labels) + " , \n")
        with open(os.path.join(args.outdir, stem + "_GofR.csv"), "w", encoding="utf-8", newline="\n") as f:
            f.write("r (Ang), G(r) barn, G(r) barn\n")
            for k in range(len(r)):
                f.write("%12.6f , %16.9f , %16.9f\n" % (r[k], G[k], G[k]))
        with open(os.path.join(args.outdir, stem + "_FofQ.csv"), "w", encoding="utf-8", newline="\n") as f:
            f.write("Q (Ang^-1), F(Q) barn, F(Q) barn\n")
            for k in range(len(q)):
                f.write("%12.6f , %16.9f , %16.9f\n" % (q[k], F[k], F[k]))
        if not args.quiet:
            print("pdf %s: %d partials, G(0) = %.4f barn, %d r points, %d Q points -> %s"
                  % (stem, len(labels), G[0], len(r), len(q), args.outdir))
        extra.update({"G0": float(G[0]), "labels": labels})
    elif args.cmd == "coord":
        counts, hist = coordination(cfg, args.pair[0], args.pair[1], args.rmax)
        if not args.quiet:
            print("coordination %s around %s within %.2f A: mean %.3f, histogram %s"
                  % (args.pair[1], args.pair[0], args.rmax, counts.mean(), hist))
        extra.update({"mean": float(counts.mean()), "histogram": hist})
    else:
        ang = bond_angles(cfg, *args.triplet, args.rmax)
        h, edges = np.histogram(ang, bins=np.arange(0.0, 180.0 + args.dangle, args.dangle))
        name = stem + "_angles_%s-%s-%s.csv" % (args.triplet[1], args.triplet[0], args.triplet[2])
        with open(os.path.join(args.outdir, name), "w", encoding="utf-8", newline="\n") as f:
            f.write("angle (deg), count\n")
            for k in range(len(h)):
                f.write("%8.2f , %d\n" % (0.5 * (edges[k] + edges[k + 1]), h[k]))
        if not args.quiet:
            print("angles %s-%s-%s: %d angles, mean %.2f deg"
                  % (args.triplet[1], args.triplet[0], args.triplet[2], len(ang), ang.mean() if len(ang) else float("nan")))
        extra.update({"n_angles": int(len(ang))})
    write_audit_log(args.log_dir, argv, True, extra=extra)
    return 0


# ----------------------------------------------------------------------------
# audit log (rule 12), selftest, CLI (rule 11)
# ----------------------------------------------------------------------------
def write_audit_log(log_dir, argv, ok, checks=None, extra=None):
    os.makedirs(log_dir, exist_ok=True)
    stamp = _dt.datetime.now().strftime("%Y%m%dT%H%M%S%f")
    rec = {"tool": "rmcprofile_tools", "version": __version__, "timestamp": stamp, "argv": list(argv),
           "ok": bool(ok), "checks": checks or [], **(extra or {})}
    path = os.path.join(log_dir, "rmcprofile_tools_%s.json" % stamp)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(rec, f, indent=2)
    return path


def selftest(outdir):
    """Round-trip every format on synthetic files written into `outdir`."""
    os.makedirs(outdir, exist_ok=True)
    checks = []

    def rec(name, ok, detail=""):
        checks.append({"name": name, "ok": bool(ok), "detail": detail})

    cfg = Rmc6f(atom_types=["Na", "Cl"], counts=[4, 4], cell=(5.64, 5.64, 5.64, 90, 90, 90), lattice=5.64 * np.eye(3),
                supercell=(1, 1, 1), density=8 / 5.64 ** 3,
                atoms=np.array(["Na"] * 4 + ["Cl"] * 4, dtype=object),
                frac=np.array([[0, 0, 0], [.5, .5, 0], [.5, 0, .5], [0, .5, .5],
                               [.5, 0, 0], [0, .5, 0], [0, 0, .5], [.5, .5, .5]], float),
                site=np.arange(1, 9), cellidx=np.zeros((8, 3), int))
    p = os.path.join(outdir, "selftest.rmc6f")
    cfg.write(p)
    back = read_rmc6f(p)
    rec("rmc6f round trip", back.n_atoms() == 8 and np.allclose(back.frac, cfg.frac) and back.atom_types == ["Na", "Cl"])

    x = np.arange(0.02, 10.0, 0.02)
    y = np.sin(x)
    q = os.path.join(outdir, "selftest_gr.dat")
    write_data_file(q, x, y, "selftest")
    df = read_data_file(q)
    rec("data file round trip", np.allclose(df.x, x) and np.allclose(df.y, y))

    dat = DatFile(scalars={"TITLE": "selftest", "NUMBER_DENSITY": "%.6f Angstrom^(-3)" % cfg.density,
                           "MINIMUM_DISTANCES": "3.5 2.4 3.5 Angstrom", "MAXIMUM_MOVES": "0.05 0.05 Angstrom",
                           "R_SPACING": "0.0200 Angstrom", "TIME_LIMIT": "1.00 MINUTES", "SAVE_PERIOD": "0.5 MINUTES"},
                  atoms=["Na", "Cl"])
    dat.order = [("scalar", k) for k in dat.scalars] + [("atoms",)]
    dat.blocks.append(DatBlock("NEUTRON_REAL_SPACE_DATA", "1",
                               [("FILENAME", "selftest_gr.dat"), ("DATA_TYPE", "G(r)"), ("FIT_TYPE", "G(r)"),
                                ("START_POINT", "1"), ("END_POINT", "400"), ("WEIGHT", "0.05")]))
    dat.order.append(("block", 0))
    dp = os.path.join(outdir, "selftest.dat")
    dat.write(dp)
    rd = read_dat(dp)
    rec("dat round trip", rd.get("NEUTRON_REAL_SPACE_DATA", "END_POINT") == "400" and rd.atoms == ["Na", "Cl"])

    findings = check_input_set("selftest", outdir)
    rec("checker on a consistent set", not [f for f in findings if f.level == "ERROR"],
        "; ".join("%s %s" % (f.level, f.code) for f in findings))

    pkg = find_package()
    rec("package located" if pkg else "package absent (RMCPROFILE_HOME unset) - skipped", True,
        pkg.home if pkg else "")
    return checks


def build_parser():
    common = argparse.ArgumentParser(add_help=False)          # accepted before or after the subcommand
    common.add_argument("--outdir", default="out", help="where outputs and selftest files are written")
    common.add_argument("--log-dir", default="logs", help="where the JSON audit log is written")
    common.add_argument("-q", "--quiet", action="store_true", help="print only the verdict")
    ap = argparse.ArgumentParser(prog="rmcprofile_tools", description=__doc__.splitlines()[0], parents=[common])
    ap.add_argument("--version", action="version", version="rmcprofile-skill %s" % __version__)
    ap.add_argument("--selftest", action="store_true", help="round-trip every format on synthetic files and exit 0/1")
    sub = ap.add_subparsers(dest="cmd")
    c = sub.add_parser("check", help="check an RMCProfile input set", parents=[common])
    c.add_argument("stem")
    c.add_argument("--dir", default=".", help="directory holding the input set")
    r = sub.add_parser("run", help="run rmcprofile <stem> with the package found through --home / RMCPROFILE_HOME",
                       parents=[common])
    r.add_argument("stem")
    r.add_argument("--dir", default=".", help="directory holding the input set")
    r.add_argument("--home", default=None, help="RMCProfile_package directory (default: $RMCPROFILE_HOME)")
    r.add_argument("--timeout", type=float, default=None, help="kill the run after this many minutes")
    p = sub.add_parser("pdf", help="partial g(r), G(r) and F(Q) from a .rmc6f configuration", parents=[common])
    p.add_argument("rmc6f")
    p.add_argument("--rmax", type=float, default=20.0, help="largest r of the partials (must be below half the shortest cell edge)")
    p.add_argument("--dr", type=float, default=0.02, help="r step (Angstrom)")
    p.add_argument("--qmax", type=float, default=30.0, help="largest Q of F(Q) (1/Angstrom)")
    p.add_argument("--dq", type=float, default=0.02, help="Q step")
    p.add_argument("--radiation", choices=["neutron", "xray"], default="neutron", help="weights for G(r)")
    p.add_argument("--grid", choices=["rmcprofile", "centre"], default="rmcprofile",
                   help="r grid: RMCProfile's k*dr (default) or bin centres")
    k = sub.add_parser("coord", help="coordination-number histogram for a pair within --rmax", parents=[common])
    k.add_argument("rmc6f")
    k.add_argument("--pair", nargs=2, required=True, metavar=("A", "B"), help="central atom type A, neighbour type B")
    k.add_argument("--rmax", type=float, required=True, help="neighbour cutoff (Angstrom)")
    a = sub.add_parser("angles", help="B-A-C bond-angle distribution with A-B, A-C within --rmax", parents=[common])
    a.add_argument("rmc6f")
    a.add_argument("--triplet", nargs=3, required=True, metavar=("A", "B", "C"), help="apex A, arms B and C")
    a.add_argument("--rmax", type=float, required=True, help="bond cutoff (Angstrom)")
    a.add_argument("--dangle", type=float, default=2.0, help="histogram bin (degrees)")
    return ap


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    args = build_parser().parse_args(argv)
    if args.selftest:
        checks = selftest(args.outdir)
        ok = all(c["ok"] for c in checks)
        if not args.quiet:
            for c in checks:
                print("[%s] %s%s" % ("PASS" if c["ok"] else "FAIL", c["name"], (" - " + c["detail"]) if c["detail"] else ""))
        write_audit_log(args.log_dir, argv, ok, checks)
        print("rmcprofile_tools selftest: %s" % ("ALL CHECKS PASSED" if ok else "FAILED"))
        return 0 if ok else 1
    if args.cmd == "check":
        findings = check_input_set(args.stem, args.dir)
        for f in findings:
            print("%s %s: %s" % (f.level, f.code, f.message))
        ok = not any(f.level == "ERROR" for f in findings)
        write_audit_log(args.log_dir, argv, ok, [{"name": f.code, "ok": f.level != "ERROR", "detail": f.message} for f in findings])
        return 0 if ok else 1
    if args.cmd == "run":
        pkg = find_package(args.home)
        if pkg is None:
            print("ERROR: no RMCProfile package: pass --home or set RMCPROFILE_HOME to the RMCProfile_package directory")
            return 2
        findings = check_input_set(args.stem, args.dir)
        errors = [f for f in findings if f.level == "ERROR"]
        if errors:
            for f in errors:
                print("ERROR %s: %s" % (f.code, f.message))
            print("not started: fix the input set first")
            return 1
        res = run_rmcprofile(args.stem, args.dir, pkg, timeout_min=args.timeout)
        print("rmcprofile %s: rc=%s, %.1f s, %d output file(s), log %s"
              % (args.stem, res.returncode, res.seconds, len(res.outputs), res.log_path))
        if res.final_chi2:
            print("final: " + ", ".join("%s=%s" % kv for kv in res.final_chi2.items()))
        write_audit_log(args.log_dir, argv, res.returncode == 0,
                        extra={"package": pkg.home, "seconds": res.seconds, "outputs": res.outputs, "final_chi2": res.final_chi2})
        return 0 if res.returncode == 0 else 1
    if args.cmd in ("pdf", "coord", "angles"):
        return _analysis_main(args, argv)
    build_parser().print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())


# ----------------------------------------------------------------------------
# building, folding and exporting configurations  (manual §2.16, §4.11)
# ----------------------------------------------------------------------------
def lattice_from_cell(cell):
    """Row vectors (Å) of a general (a, b, c, alpha, beta, gamma) cell, a along x, b in the xy plane."""
    a, b, c, al, be, ga = cell
    al, be, ga = np.radians([al, be, ga])
    va = np.array([a, 0.0, 0.0])
    vb = np.array([b * np.cos(ga), b * np.sin(ga), 0.0])
    cx = c * np.cos(be)
    cy = c * (np.cos(al) - np.cos(be) * np.cos(ga)) / np.sin(ga)
    cz = np.sqrt(max(c * c - cx * cx - cy * cy, 0.0))
    return np.array([va, vb, [cx, cy, cz]])


def build_configuration(cell, sites, supercell, title="built by rmcprofile-skill"):
    """A supercell configuration from a unit cell.

    cell = (a, b, c, alpha, beta, gamma); sites = [(label, x, y, z), ...] fractional in the unit
    cell (one entry per atom of the cell, any order); supercell = (na, nb, nc). Atoms are
    ordered by type (the order of first appearance in `sites`), then by cell, then by site —
    the order RMCProfile's 'ATOMS ::' line and the partials expect."""
    na, nb, nc = supercell
    types = []
    for lab, *_ in sites:
        if lab not in types:
            types.append(lab)
    atoms, frac, site_no, cellidx = [], [], [], []
    for t in types:
        for i, j, k in np.ndindex(na, nb, nc):
            for s, (lab, x, y, z) in enumerate(sites):
                if lab == t:
                    atoms.append(lab)
                    frac.append([(x + i) / na, (y + j) / nb, (z + k) / nc])
                    site_no.append(s + 1)
                    cellidx.append([i, j, k])
    lat = lattice_from_cell(cell)
    big = lat * np.array([[na], [nb], [nc]])
    N = len(atoms)
    cfg = Rmc6f(header={"Metadata title": title}, atom_types=types, counts=[atoms.count(t) for t in types],
                cell=(cell[0] * na, cell[1] * nb, cell[2] * nc, cell[3], cell[4], cell[5]),
                lattice=big, supercell=(na, nb, nc), density=N / abs(np.linalg.det(big)),
                atoms=np.array(atoms, dtype=object), frac=np.array(frac, float) % 1.0,
                site=np.array(site_no, int), cellidx=np.array(cellidx, int))
    return cfg


def fold_to_unit_cell(cfg):
    """Fractional coordinates of every atom inside its unit cell and the cell it came from,
    using the supercell dimensions of the header."""
    n = np.array(cfg.supercell, float)
    scaled = (cfg.frac % 1.0) * n
    idx = np.floor(scaled + 1e-9).astype(int) % np.array(cfg.supercell)
    frac_cell = (scaled - idx) % 1.0
    return frac_cell, idx


def export_xyz(cfg, path, comment=None):
    xyz = cfg.cart()
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("%d\n%s\n" % (cfg.n_atoms(), comment or "rmcprofile-skill export (Angstrom)"))
        for lab, (x, y, z) in zip(cfg.atoms, xyz):
            f.write("%-3s %12.6f %12.6f %12.6f\n" % (lab, x, y, z))


def export_cif(cfg, path, name="rmcprofile_skill_box"):
    """P1 CIF of the whole supercell (every atom explicit)."""
    a, b, c, al, be, ga = cfg.cell
    lines = ["data_%s" % name, "_symmetry_space_group_name_H-M   'P 1'", "_symmetry_Int_Tables_number   1",
             "_cell_length_a   %.6f" % a, "_cell_length_b   %.6f" % b, "_cell_length_c   %.6f" % c,
             "_cell_angle_alpha   %.4f" % al, "_cell_angle_beta   %.4f" % be, "_cell_angle_gamma   %.4f" % ga,
             "loop_", "_atom_site_label", "_atom_site_type_symbol", "_atom_site_fract_x", "_atom_site_fract_y",
             "_atom_site_fract_z"]
    for i, (lab, (x, y, z)) in enumerate(zip(cfg.atoms, cfg.frac)):
        lines.append("%s%d %s %.6f %.6f %.6f" % (lab, i + 1, lab, x, y, z))
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


# ----------------------------------------------------------------------------
# Faber-Ziman partials, X-ray form factors and weights  (manual §4.3, App. D)
# ----------------------------------------------------------------------------
def faber_ziman_sq(r, g, density, q):
    """S_ij(Q) - 1 = 4 pi rho0 int r^2 (g_ij(r) - 1) sin(Qr)/(Qr) dr."""
    r = np.asarray(r, float)
    g = np.asarray(g, float)
    q = np.asarray(q, float)
    dr = np.diff(r).mean()
    qr = np.outer(q, r)
    safe = np.where(qr == 0, 1.0, qr)
    kernel = np.where(qr == 0, 1.0, np.sin(qr) / safe)
    return 4 * np.pi * density * (kernel * (r ** 2 * (g - 1.0) * dr)).sum(axis=1)


def xray_form_factor(symbol, q):
    """Cromer-Mann X-ray atomic form factor f(Q) (electrons) from the `periodictable` package."""
    try:
        from periodictable import cromermann
    except ImportError as exc:      # pragma: no cover - depends on the environment
        raise ImportError("X-ray form factors need the optional 'periodictable' package "
                          "(pip install periodictable)") from exc
    return np.asarray(cromermann.fxrayatq(symbol, np.asarray(q, float)), float)


def xray_weights(cfg, q):
    """Q-dependent X-ray weights w_ij(Q) = (2 - delta_ij) c_i c_j f_i f_j / (sum c f)^2, summing to 1."""
    n = float(sum(cfg.counts))
    c = {t: k / n for t, k in zip(cfg.atom_types, cfg.counts)}
    f = {t: xray_form_factor(t, q) for t in cfg.atom_types}
    mean = sum(c[t] * f[t] for t in cfg.atom_types)
    w = {}
    for i, a in enumerate(cfg.atom_types):
        for b in cfg.atom_types[i:]:
            mult = 1.0 if a == b else 2.0
            w["%s-%s" % (a, b)] = mult * c[a] * c[b] * f[a] * f[b] / mean ** 2
    return w


def total_fq_from_partials(r, partials, cfg, q, radiation="neutron"):
    """F(Q) from the partials: neutron = sum w_ij (S_ij - 1) (barn, equals fq_from_gr(total_gr));
    X-ray = sum c_i c_j f_i(Q) f_j(Q) (S_ij - 1) / (sum c_i f_i(Q))^2 (normalised)."""
    q = np.asarray(q, float)
    S = {lab: faber_ziman_sq(r, partials[lab], cfg.density, q) for lab in partials}
    if radiation == "neutron":
        w = neutron_weights(cfg)
        return sum(w[lab] * S[lab] for lab in S)
    if radiation == "xray":
        w = xray_weights(cfg, q)
        return sum(w[lab] * S[lab] for lab in S)
    raise ValueError("radiation must be 'neutron' or 'xray'")


ATOMIC_NUMBER = {"H": 1, "D": 1, "Li": 3, "Be": 4, "B": 5, "C": 6, "N": 7, "O": 8, "F": 9, "Na": 11, "Mg": 12, "Al": 13,
                 "Si": 14, "P": 15, "S": 16, "Cl": 17, "K": 19, "Ca": 20, "Sc": 21, "Ti": 22, "V": 23, "Cr": 24, "Mn": 25,
                 "Fe": 26, "Co": 27, "Ni": 28, "Cu": 29, "Zn": 30, "Ga": 31, "Ge": 32, "As": 33, "Se": 34, "Br": 35,
                 "Rb": 37, "Sr": 38, "Y": 39, "Zr": 40, "Nb": 41, "Mo": 42, "Ag": 47, "Cd": 48, "In": 49, "Sn": 50,
                 "Sb": 51, "Te": 52, "I": 53, "Cs": 55, "Ba": 56, "La": 57, "Ce": 58, "Nd": 60, "Gd": 64, "Hf": 72,
                 "Ta": 73, "W": 74, "Pt": 78, "Au": 79, "Hg": 80, "Tl": 81, "Pb": 82, "Bi": 83, "Th": 90, "U": 92}


def xray_coefficients_rmcprofile(cfg):
    """Manual Appendix D: treat X-ray G(r) as neutron data with b -> Z, coefficients
    (2 - delta_ij) c_i c_j Z_i Z_j normalised to sum to 1 (the NEUTRON_COEFFICIENTS line)."""
    n = float(sum(cfg.counts))
    c = {t: k / n for t, k in zip(cfg.atom_types, cfg.counts)}
    raw = {}
    for i, a in enumerate(cfg.atom_types):
        for b in cfg.atom_types[i:]:
            mult = 1.0 if a == b else 2.0
            raw["%s-%s" % (a, b)] = mult * c[a] * c[b] * ATOMIC_NUMBER[a] * ATOMIC_NUMBER[b]
    tot = sum(raw.values())
    return {k: v / tot for k, v in raw.items()}


def cromer_mann_4term(symbol, smax=2.0):
    """Fit the 4-Gaussian Cromer-Mann form a1..a4, b1..b4, c (the layout of RMCProfile's .xray
    file) to periodictable's f(s), s = Q/4pi in 1/Angstrom, on [0, smax]. Returns 9 numbers."""
    from scipy.optimize import curve_fit
    s = np.linspace(0.0, smax, 401)
    f = xray_form_factor(symbol, 4 * np.pi * s)

    def model(s, a1, b1, a2, b2, a3, b3, a4, b4, c):
        return (a1 * np.exp(-b1 * s * s) + a2 * np.exp(-b2 * s * s) + a3 * np.exp(-b3 * s * s)
                + a4 * np.exp(-b4 * s * s) + c)
    z = f[0]
    p0 = [z * 0.4, 3.0, z * 0.3, 10.0, z * 0.2, 0.5, z * 0.05, 60.0, z * 0.05]
    popt, _ = curve_fit(model, s, f, p0=p0, maxfev=20000)
    return [float(v) for v in popt]


def write_xray_file(path, symbols):
    """RMCProfile's .xray file: one line per atom type, 'SYMBOL a1 b1 a2 b2 a3 b3 a4 b4 c'."""
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        for sym in symbols:
            coef = cromer_mann_4term(sym)
            f.write("%-2s " % sym.upper() + " ".join("%9.4f" % v for v in coef) + "\n")


# ----------------------------------------------------------------------------
# a complete input set from a box and synthetic data  (manual §3.2)
# ----------------------------------------------------------------------------
def write_input_set(stem, directory, cfg, *, gr=None, fq=None, weights=(0.05, 0.01), min_dist, max_move,
                    time_limit_min, r_spacing=0.02, title="rmcprofile-skill synthetic run", extra_blocks=(),
                    save_period_min=None, print_period=1000, ignore_history=True,
                    flags=("NO_MOVEOUT", "NO_SAVE_CONFIGURATIONS", "NO_RESOLUTION_CONVOLUTION")):
    """Write <stem>.rmc6f, <stem>_gr.dat / <stem>_fq.dat (two-line layout) and <stem>.dat.

    min_dist: {pair label: Angstrom} in the manual's pair order (missing pairs get 0.0);
    max_move: float or {type: Angstrom}; gr = (r, G) in barn; fq = (q, F) in barn;
    extra_blocks: DatBlock instances appended before END. save_period_min defaults to the time
    limit (one save at the end); ignore_history=True writes IGNORE_HISTORY_FILE :: so that a
    <stem>.his6f left by an earlier pass is not read — a history file written by a zero-move
    pass makes the next run compute an empty PDF and crawl (P-15, 2026-09-05). Returns the paths."""
    if save_period_min is None:
        save_period_min = time_limit_min
    d = str(directory)
    os.makedirs(d, exist_ok=True)
    paths = []
    cfg.write(os.path.join(d, stem + ".rmc6f"))
    paths.append(os.path.join(d, stem + ".rmc6f"))
    labels = pair_labels(cfg.atom_types)
    mm = max_move if isinstance(max_move, dict) else {t: max_move for t in cfg.atom_types}
    dat = DatFile()
    scal = [("TITLE", title), ("MATERIAL", "".join(cfg.atom_types)), ("INVESTIGATOR", "rmcprofile-skill"),
            ("NUMBER_DENSITY", "%.8f Angstrom^(-3)" % cfg.density),
            ("MINIMUM_DISTANCES", " ".join("%.3f" % min_dist.get(lab, 0.0) for lab in labels) + " Angstrom"),
            ("MAXIMUM_MOVES", " ".join("%.3f" % mm[t] for t in cfg.atom_types) + " Angstrom"),
            ("R_SPACING", "%.4f Angstrom" % r_spacing), ("PRINT_PERIOD", str(print_period)),
            ("TIME_LIMIT", "%.2f MINUTES" % time_limit_min), ("SAVE_PERIOD", "%.2f MINUTES" % save_period_min)]
    for k, v in scal:
        dat.scalars[k] = v
        dat.order.append(("scalar", k))
    dat.atoms = list(cfg.atom_types)
    dat.order.append(("atoms",))
    dat.blocks.append(DatBlock("FLAGS", "", [(fl, None) for fl in flags]))
    dat.order.append(("block", len(dat.blocks) - 1))
    for k, v in (("INPUT_CONFIGURATION_FORMAT", "rmc6f"), ("SAVE_CONFIGURATION_FORMAT", "rmc6f")):
        dat.scalars[k] = v
        dat.order.append(("scalar", k))
    if ignore_history:
        dat.scalars["IGNORE_HISTORY_FILE"] = ""
        dat.order.append(("scalar", "IGNORE_HISTORY_FILE"))
    if gr is not None:
        r, G = gr
        fn = stem + "_gr.dat"
        write_data_file(os.path.join(d, fn), r, G, title + " G(r) barn")
        paths.append(os.path.join(d, fn))
        dat.blocks.append(DatBlock("NEUTRON_REAL_SPACE_DATA", "1",
                                   [("FILENAME", fn), ("DATA_TYPE", "G(r)"), ("FIT_TYPE", "G(r)"), ("START_POINT", "1"),
                                    ("END_POINT", str(len(r))), ("CONSTANT_OFFSET", "0.0000"),
                                    ("WEIGHT", "%.4f" % weights[0]), ("NO_FITTED_OFFSET", None), ("NO_FITTED_SCALE", None)]))
        dat.order.append(("block", len(dat.blocks) - 1))
    if fq is not None:
        q, F = fq
        fn = stem + "_fq.dat"
        write_data_file(os.path.join(d, fn), q, F, title + " F(Q) barn")
        paths.append(os.path.join(d, fn))
        dat.blocks.append(DatBlock("NEUTRON_RECIPROCAL_SPACE_DATA", "1",
                                   [("FILENAME", fn), ("DATA_TYPE", "F(Q)"), ("FIT_TYPE", "F(Q)"), ("START_POINT", "1"),
                                    ("END_POINT", str(len(q))), ("CONSTANT_OFFSET", "0.0000"),
                                    ("WEIGHT", "%.4f" % weights[1]), ("CONVOLVE", ""), ("NO_FITTED_OFFSET", None),
                                    ("NO_FITTED_SCALE", None)]))
        dat.order.append(("block", len(dat.blocks) - 1))
    for blk in extra_blocks:
        dat.blocks.append(blk)
        dat.order.append(("block", len(dat.blocks) - 1))
    dat.write(os.path.join(d, stem + ".dat"))
    paths.append(os.path.join(d, stem + ".dat"))
    return paths


def bond_valence_sum(cfg, centre, neighbour, r0, b=0.37, cutoff=3.5):
    """Bond valence sum on every atom of type `centre` from neighbours of type `neighbour`:
    sum exp((r0 - d)/b) over d < cutoff (Brese & O'Keeffe 1991; manual §2.7, App. C)."""
    dist = _min_image_distances(cfg)
    ia, ib = np.where(cfg.atoms == centre)[0], np.where(cfg.atoms == neighbour)[0]
    block = dist[np.ix_(ia, ib)]
    contrib = np.where(block < cutoff, np.exp((r0 - block) / b), 0.0)
    return contrib.sum(axis=1)
